// Golden values generated by running the ACTUAL dvm_composite.py
// momentum()/durability() functions, plus main()'s own valuation-rank +
// classification + composite lines re-executed directly against a small
// synthetic 3-stock, cross-market table (no fundamentals_cache.db/parquet
// I/O involved) -- see the commit message / PR description for the full
// generation script.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/dvm_composite.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {

constexpr std::size_t kN = 260;

std::vector<double> gen_close(double seedbase, double trendslope, double wobble_amp,
                              double wobble_period, int rally_start = -1,
                              double rally_slope = 0.0) {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 + trendslope * di + wobble_amp * std::sin(di / wobble_period + seedbase);
    if (rally_start >= 0 && static_cast<int>(i) >= rally_start) {
      v += static_cast<double>(static_cast<int>(i) - rally_start + 1) * rally_slope;
    }
    out[i] = v;
  }
  return out;
}

}  // namespace

TEST_CASE("dvm_composite_momentum matches dvm_composite.py's momentum()", "[dvm_composite]") {
  auto closeA = gen_close(0.3, 0.12, 3.0, 12.0, /*rally_start=*/230, /*rally_slope=*/1.3);
  auto closeB = gen_close(1.7, -0.04, 2.5, 9.0);
  auto closeC = gen_close(2.9, 0.02, 5.0, 15.0);

  CHECK(dvm_composite_momentum(closeA) == Approx(75.0000000000).epsilon(1e-6));
  CHECK(dvm_composite_momentum(closeB) == Approx(49.3702914656).epsilon(1e-6));
  CHECK(dvm_composite_momentum(closeC) == Approx(75.0000000000).epsilon(1e-6));
}

TEST_CASE("dvm_composite_momentum returns NaN below the 200-bar minimum", "[dvm_composite]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0);
  close.resize(199);
  CHECK(std::isnan(dvm_composite_momentum(close)));
}

TEST_CASE("dvm_composite_durability matches dvm_composite.py's dynamic-subs formula",
          "[dvm_composite]") {
  // rowA: all 5 present -> mean of (90,90,85,85,75) = 85.0
  double dA = dvm_composite_durability(25.0, 0.3, 20.0, 25.0, 5.0);
  CHECK(dA == Approx(85.0000000000).epsilon(1e-9));

  // rowB: roe and rev_growth absent -> mean of just (de=70, op_margin=40, earn_growth=35) = 40.0
  double dB = dvm_composite_durability(std::nullopt, 1.5, std::nullopt, 5.0, -2.0);
  CHECK(dB == Approx(40.0000000000).epsilon(1e-9));

  // rowC: de/op_margin/earn_growth absent -> mean of just (roe=55, rev_growth=60) = 57.5
  double dC = dvm_composite_durability(12.0, std::nullopt, 10.0, std::nullopt, std::nullopt);
  CHECK(dC == Approx(57.5000000000).epsilon(1e-9));

  // Nothing present -> NaN, not a substituted default (unlike dvm_engine.py's durability_score())
  double dNone =
      dvm_composite_durability(std::nullopt, std::nullopt, std::nullopt, std::nullopt, std::nullopt);
  CHECK(std::isnan(dNone));
}

TEST_CASE("build_dvm_composite matches dvm_composite.py's full main() pipeline",
          "[dvm_composite]") {
  DvmCompositeInput a;
  a.market = "US";
  a.ticker = "A";
  a.close = gen_close(0.3, 0.12, 3.0, 12.0, 230, 1.3);
  a.roe = 25.0;
  a.de = 0.3;
  a.rev_growth = 20.0;
  a.op_margin = 25.0;
  a.earn_growth = 5.0;
  a.pe = 10.0;
  a.pb = 2.0;

  DvmCompositeInput b;
  b.market = "US";
  b.ticker = "B";
  b.close = gen_close(1.7, -0.04, 2.5, 9.0);
  b.roe = std::nullopt;
  b.de = 1.5;
  b.rev_growth = std::nullopt;
  b.op_margin = 5.0;
  b.earn_growth = -2.0;
  b.pe = -5.0;  // negative PE -> earnings yield undefined
  b.pb = 1.0;

  DvmCompositeInput c;
  c.market = "JP";
  c.ticker = "C";
  c.close = gen_close(2.9, 0.02, 5.0, 15.0);
  c.roe = 12.0;
  c.de = std::nullopt;
  c.rev_growth = 10.0;
  c.op_margin = std::nullopt;
  c.earn_growth = std::nullopt;
  c.pe = 20.0;
  c.pb = std::nullopt;  // missing P/B

  auto rows = build_dvm_composite({a, b, c});
  REQUIRE(rows.size() == 3);

  auto find = [&](const std::string& t) -> const DvmCompositeRow& {
    for (const auto& r : rows)
      if (r.ticker == t) return r;
    throw std::runtime_error("not found");
  };

  const auto& ra = find("A");
  CHECK(ra.M == Approx(75.0));
  CHECK(ra.D == Approx(85.0));
  CHECK(ra.V == Approx(60.0));
  CHECK(ra.code == "GGG");
  CHECK(ra.label == "Strong Performer");
  CHECK(ra.composite == Approx(73.3));

  const auto& rb = find("B");
  CHECK(rb.M == Approx(49.4));
  CHECK(rb.D == Approx(40.0));
  CHECK(rb.V == Approx(65.0));
  CHECK(rb.code == "BGB");
  CHECK(rb.label == "Deep Value / Watch");
  CHECK(rb.composite == Approx(51.5));

  const auto& rc = find("C");
  CHECK(rc.M == Approx(75.0));
  CHECK(rc.D == Approx(57.5));
  CHECK(rc.V == Approx(40.0));
  CHECK(rc.code == "GBG");
  CHECK(rc.label == "Expensive Durable Mover");
  CHECK(rc.composite == Approx(57.5));
}

TEST_CASE("build_dvm_composite drops stocks missing momentum or durability",
          "[dvm_composite]") {
  DvmCompositeInput tooShort;
  tooShort.market = "US";
  tooShort.ticker = "SHORT";
  tooShort.close = gen_close(0.0, 0.1, 1.0, 10.0);
  tooShort.close.resize(50);  // below the 200-bar minimum -> M is NaN
  tooShort.roe = 20.0;

  DvmCompositeInput noFundamentals;
  noFundamentals.market = "US";
  noFundamentals.ticker = "NOFUND";
  noFundamentals.close = gen_close(1.0, 0.1, 1.0, 10.0);
  // every durability input left as nullopt -> D is NaN

  auto rows = build_dvm_composite({tooShort, noFundamentals});
  CHECK(rows.empty());
}
