// Golden values generated by running ml_signal_engine.py's actual
// z_score_normalise() on small fixed matrices.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "bazaartalks/quant_core/ml_signal_engine.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

// python3: z_score_normalise(np.array([[1,10],[2,20],[3,20],[4,40]]))
TEST_CASE("z_score_normalize_window matches Python's per-column z-score", "[ml_signal_engine]") {
  Eigen::MatrixXd X(4, 2);
  X << 1.0, 10.0, 2.0, 20.0, 3.0, 20.0, 4.0, 40.0;
  auto z = z_score_normalize_window(X);
  CHECK(z(0, 0) == Approx(-1.3416407864998738));
  CHECK(z(0, 1) == Approx(-1.1470786693528088));
  CHECK(z(1, 0) == Approx(-0.4472135954999579));
  CHECK(z(1, 1) == Approx(-0.22941573387056174));
  CHECK(z(3, 0) == Approx(1.3416407864998738));
  CHECK(z(3, 1) == Approx(1.6059101370939324));
}

// python3: z_score_normalise(np.array([[5,1],[5,2],[5,3]])) -- first
// column is degenerate (all 5s) -> std[std==0]=1, so it maps to all-0.0,
// NOT NaN (distinct from z_rank()'s all-NaN degenerate convention).
TEST_CASE("z_score_normalize_window maps a zero-variance column to all-zero, not NaN",
          "[ml_signal_engine]") {
  Eigen::MatrixXd X(3, 2);
  X << 5.0, 1.0, 5.0, 2.0, 5.0, 3.0;
  auto z = z_score_normalize_window(X);
  CHECK(z(0, 0) == Approx(0.0));
  CHECK(z(1, 0) == Approx(0.0));
  CHECK(z(2, 0) == Approx(0.0));
  CHECK(z(0, 1) == Approx(-1.224744871391589));
  CHECK(z(1, 1) == Approx(0.0));
  CHECK(z(2, 1) == Approx(1.224744871391589));
}

TEST_CASE("make_sequences produces (n - lookback - predict_days) samples", "[ml_signal_engine]") {
  int n = 20, lookback = 5, predict_days = 2, n_feat = 3;
  Eigen::MatrixXd features = Eigen::MatrixXd::Random(n, n_feat);
  Eigen::VectorXd target = Eigen::VectorXd::Random(n);
  auto seq = make_sequences(features, target, lookback, predict_days);
  CHECK(seq.X.rows() == n - lookback - predict_days);
  CHECK(seq.X.cols() == lookback * n_feat);
  CHECK(seq.y.size() == n - lookback - predict_days);
}
