// Golden values generated by running factor_research.py's actual
// markowitz() scoring logic against a fixed synthetic 5-asset
// covariance/mean-return estimate and realised forward returns.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "bazaartalks/quant_core/factor_research.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
Matrix sample_cov() {
  Matrix cov(5, 5);
  cov << 0.022485194048521735, -0.0007040534109445277, 0.0011023491546203255,
      0.001895895125191855, -0.000557378637732307, -0.0007040534109445277, 0.028548961119313414,
      0.0009213405272252045, -0.0027156734385484316, 0.000803934315721694,
      0.0011023491546203255, 0.0009213405272252045, 0.028971901519597616, 0.0015949803002036785,
      0.004220162189652149, 0.001895895125191855, -0.0027156734385484316, 0.0015949803002036785,
      0.024728370539399448, -0.00026770811524436046, -0.000557378637732307, 0.000803934315721694,
      0.004220162189652149, -0.00026770811524436046, 0.026583036293274943;
  return cov;
}
Vector sample_mu() {
  Vector mu(5);
  mu << 0.12147918866716262, 0.1715924930462025, 0.17638906762874637, 0.0675045544401366,
      -0.13913461597592305;
  return mu;
}
Vector sample_fwd() {
  Vector fwd(5);
  fwd << 5.0, 12.0, -3.0, 8.0, 20.0;
  return fwd;
}
}  // namespace

// python3: markowitz's four-portfolio comparison on this fixture ->
//   Concentrated(1)  -3.0   17.02  -0.18
//   EqualWeight       8.4    7.59   1.11
//   MinVariance       8.91   7.48   1.19
//   MaxSharpe        -1.77  14.1   -0.13
TEST_CASE("markowitz_portfolios matches Python's four-portfolio comparison", "[factor_research]") {
  auto result = markowitz_portfolios(sample_mu(), sample_cov(), sample_fwd());

  CHECK(result.concentrated.fwd_ret_pct == Approx(-3.0));
  CHECK(result.concentrated.ex_ante_vol_pct == Approx(17.02).margin(0.01));
  CHECK(result.concentrated.ret_over_vol == Approx(-0.18).margin(0.01));

  CHECK(result.equal_weight.fwd_ret_pct == Approx(8.4));
  CHECK(result.equal_weight.ex_ante_vol_pct == Approx(7.59).margin(0.01));
  CHECK(result.equal_weight.ret_over_vol == Approx(1.11).margin(0.01));

  CHECK(result.min_variance.fwd_ret_pct == Approx(8.91).margin(0.01));
  CHECK(result.min_variance.ex_ante_vol_pct == Approx(7.48).margin(0.01));
  CHECK(result.min_variance.ret_over_vol == Approx(1.19).margin(0.01));

  CHECK(result.max_sharpe.fwd_ret_pct == Approx(-1.77).margin(0.01));
  CHECK(result.max_sharpe.ex_ante_vol_pct == Approx(14.1).margin(0.01));
  CHECK(result.max_sharpe.ret_over_vol == Approx(-0.13).margin(0.01));
}

TEST_CASE("markowitz_portfolios' concentrated pick is a one-hot at argmax(mu)",
          "[factor_research]") {
  // mu's argmax is index 2 (0.176...) -- the concentrated portfolio's
  // realised return should equal fwd_ret_pct[2] exactly (-3.0), since a
  // one-hot weight vector just selects that single asset's return.
  auto result = markowitz_portfolios(sample_mu(), sample_cov(), sample_fwd());
  CHECK(result.concentrated.fwd_ret_pct == Approx(sample_fwd()(2)));
}
