// Golden values generated by running quality_factor.py's actual
// functions on fixed synthetic fixtures.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>
#include <limits>

#include "bazaartalks/quant_core/quality_factor.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
constexpr double kNaN = std::numeric_limits<double>::quiet_NaN();
}

// python3: z_rank(pd.Series([10.0,20.0,15.0,nan,25.0,5.0]))
// -> [-0.7071067811865475, 0.7071067811865475, 0.0, nan, 1.414213562373095, -1.414213562373095]
TEST_CASE("z_rank matches Python's rank-then-zscore with NaN passthrough", "[quality_factor]") {
  std::vector<double> v = {10.0, 20.0, 15.0, kNaN, 25.0, 5.0};
  auto z = z_rank(v);
  REQUIRE(z.size() == 6);
  CHECK(z[0] == Approx(-0.7071067811865475));
  CHECK(z[1] == Approx(0.7071067811865475));
  CHECK(z[2] == Approx(0.0));
  CHECK(std::isnan(z[3]));
  CHECK(z[4] == Approx(1.414213562373095));
  CHECK(z[5] == Approx(-1.414213562373095));
}

TEST_CASE("z_rank returns all-NaN (not all-zero) for a degenerate cross-section",
          "[quality_factor]") {
  std::vector<double> v = {5.0, 5.0, 5.0};
  auto z = z_rank(v);
  for (double x : z) CHECK(std::isnan(x));
}

namespace {
std::vector<QualityInputs> sample_rows() {
  return {
      {15, 8, 20, 5, 4, 0.5, 1.1, 0.25, 2.0, 1e9, 3.0},
      {20, 12, 25, 10, 9, 0.3, 0.9, 0.20, 3.0, 5e9, 4.5},
      {10, 6, 15, 3, 2, 0.8, 1.3, 0.30, 1.0, 2e8, 2.0},
      {25, 15, 30, 15, 14, 0.2, 0.8, 0.18, 4.0, 1e10, 6.0},
      {5, 3, 10, 1, 0, 1.2, 1.5, 0.35, 0.5, 1e8, 1.2},
      {18, 10, 22, 7, 6, 0.4, 1.0, 0.22, 2.5, 3e9, 3.8},
  };
}
}  // namespace

// python3: full quality_score() pipeline on the fixture above ->
//   quality_raw/quality: [-0.29277, 0.87831, -0.87831, 1.46385, -1.46385, 0.29277]
//   quality_score:       [50.0, 83.3, 33.3, 100.0, 16.7, 66.7]
TEST_CASE("quality_score_batch matches Python's full rank-zscore-composite pipeline",
          "[quality_factor]") {
  auto scores = quality_score_batch(sample_rows());
  REQUIRE(scores.size() == 6);

  std::vector<double> expected_quality = {-0.29277, 0.87831, -0.87831, 1.46385, -1.46385, 0.29277};
  std::vector<double> expected_score = {50.0, 83.3, 33.3, 100.0, 16.7, 66.7};
  for (std::size_t i = 0; i < 6; ++i) {
    CHECK(scores[i].quality == Approx(expected_quality[i]).margin(1e-4));
    CHECK(scores[i].quality_raw == Approx(expected_quality[i]).margin(1e-4));
    CHECK(scores[i].quality_score == Approx(expected_score[i]));
    // Every dimension collapses to the same value in this fixture since
    // all sub-metrics were constructed proportionally -- a real check
    // that each dimension actually ran, not just that quality did.
    CHECK(scores[i].profitability == Approx(expected_quality[i]).margin(1e-4));
  }
}

// python3: assign_deciles(quality) on the same 6-row fixture -> only row 3
// (quality=1.46385, pct-rank 1.0) clears the top=0.90 quality bar.
TEST_CASE("assign_deciles matches Python's percentile-rank thresholds", "[quality_factor]") {
  auto scores = quality_score_batch(sample_rows());
  std::vector<double> quality;
  for (auto& s : scores) quality.push_back(s.quality);
  auto deciles = assign_deciles(quality);
  std::vector<std::string> expected = {"mid", "mid", "mid", "quality", "mid", "mid"};
  CHECK(deciles == expected);
}

// python3: value_weight([1e9,5e9,2e8,1e10,1e8,3e9])
TEST_CASE("value_weight matches Python's market-cap weighting", "[quality_factor]") {
  std::vector<double> mktcap = {1e9, 5e9, 2e8, 1e10, 1e8, 3e9};
  auto w = value_weight(mktcap);
  CHECK(w[0] == Approx(0.05181347150259067));
  CHECK(w[1] == Approx(0.25906735751295334));
  CHECK(w[2] == Approx(0.010362694300518135));
  CHECK(w[3] == Approx(0.5181347150259067));
  CHECK(w[4] == Approx(0.0051813471502590676));
  CHECK(w[5] == Approx(0.15544041450777202));
  double sum = 0;
  for (double x : w) sum += x;
  CHECK(sum == Approx(1.0));
}

TEST_CASE("value_weight falls back to equal-weight when the clipped sum is 0",
          "[quality_factor]") {
  std::vector<double> mktcap = {-1.0, -2.0, 0.0};
  auto w = value_weight(mktcap);
  for (double x : w) CHECK(x == Approx(1.0 / 3.0));
}

// python3: driver_breakdown on a 40-row fixture with genuinely different
// per-dimension correlations to log(pb) -> profitability=0.931 > growth=0.638
// > safety=0.148 > payout=-0.141 (already descending in DIMENSIONS order).
TEST_CASE("driver_breakdown sorts dimensions by correlation with log(pb)", "[quality_factor]") {
  std::vector<double> profitability = {
      0.24399305,  0.77696206,  -0.26765108, 0.76024731,  0.23562339,  -0.10264243, 0.09793916,
      0.95975935,  0.56016346,  0.10094126,  0.88572182,  0.04223071,  0.64879208,  0.60669953,
      -0.22631530, 0.64383086,  -0.11420614, 1.25737774,  0.87745949,  0.53085011,  0.50297059,
      0.54496341,  0.53544602,  -0.24047961, 1.50994034,  0.43507749,  1.46592470,  -0.18029438,
      1.21778030,  0.23558209,  0.38978589,  0.74263512,  0.74758683,  -0.62204488, 0.11153397,
      0.83084435,  1.20845426,  0.94773270,  0.51263850,  0.73920998};
  std::vector<double> growth = {
      -0.17620833, 0.16370941,  -0.95088734, 0.18032615,  -0.28469142, 0.66281772,  -0.13787681,
      -0.21752783, 0.68139922,  -0.10695337, 0.42410862,  0.30346175,  0.43999349,  0.18328532,
      0.34267537,  0.54704835,  -0.10004923, 0.56815899,  0.05308796,  0.37387976,  0.29955093,
      0.52390948,  0.53586949,  -0.10286448, 1.43738975,  0.26570113,  0.68511626,  -0.16267497,
      0.69144239,  -0.18645107, 0.90006527,  0.55595151,  -0.41118439, -0.51307296, -0.59288702,
      0.81141869,  1.32180501,  0.29829308,  0.42636221,  0.36506535};
  std::vector<double> safety = {
      0.34989107,  1.18943424,  -0.20925967, -0.57052224, 0.48913448,  0.25147806,  0.43951022,
      0.77573050,  -0.27546405, -1.19435650, 0.78641079,  -0.15398888, -0.58193304, -0.56774885,
      0.66134237,  0.24359970,  0.22105249,  0.76493006,  -0.23380641, -0.57045520, -0.51006993,
      -0.55730149, -0.05866819, -0.55548026, 0.34551715,  -0.14907996, 0.22124808,  0.37859299,
      1.10434089,  0.89746619,  0.10383072,  0.28166730,  -0.20022751, 0.46778183,  0.90851611,
      -0.17237745, 0.76725049,  -0.00625583, -0.03028933, 0.29022204};
  std::vector<double> payout = {
      -0.35817266, 0.22255949,  -0.74853984, -0.60173823, -0.14696049, -0.43472527, 0.12747501,
      -0.99723843, -0.17224872, -0.69801094, -0.31542382, 0.11723469,  0.88802115,  0.33897919,
      0.83214304,  -0.16866348, 0.99890101,  -0.50267624, -0.38460000, -0.79796175, 0.10857462,
      0.36863529,  -0.49091301, -0.15395887, -0.71527652, -0.37487056, -0.69904535, -0.65809804,
      0.29512193,  -0.93173170, -0.51585722, -0.05949697, 0.34857993,  0.09941064,  -0.12578554,
      -0.25093718, -0.59383665, 0.15114510,  -0.35000884, -0.76218602};
  std::vector<double> pb = {
      1.69093369, 2.11694850, 1.00204763, 2.33217021, 1.33756292, 0.74655304, 1.19261290,
      2.22395599, 1.94667934, 0.92891474, 2.24641328, 1.57776066, 2.03915641, 1.94668237,
      0.92458700, 1.96501244, 1.21720392, 3.57330045, 2.36711237, 1.68719567, 1.00854044,
      1.69420968, 1.78594282, 0.90079815, 5.01122356, 2.00801688, 3.84271388, 0.94515525,
      3.73547046, 0.83486704, 1.19051631, 2.16241500, 1.68877451, 0.50710519, 0.94857728,
      2.50657725, 4.68298363, 2.60496823, 1.43605292, 2.45531718};

  auto result = driver_breakdown(profitability, growth, safety, payout, pb);
  REQUIRE(result.size() == 4);
  CHECK(result[0].dimension == "profitability");
  CHECK(result[0].corr_with_log_mb == Approx(0.931).margin(0.001));
  CHECK(result[1].dimension == "growth");
  CHECK(result[1].corr_with_log_mb == Approx(0.638).margin(0.001));
  CHECK(result[2].dimension == "safety");
  CHECK(result[2].corr_with_log_mb == Approx(0.148).margin(0.001));
  CHECK(result[3].dimension == "payout");
  CHECK(result[3].corr_with_log_mb == Approx(-0.141).margin(0.001));
}

TEST_CASE("price_premium returns n-only result below the 30-row minimum", "[quality_factor]") {
  std::vector<double> pb = {1.0, 2.0, 3.0};
  std::vector<double> quality = {0.1, 0.2, 0.3};
  std::vector<double> mktcap = {1e9, 2e9, 3e9};
  std::vector<std::string> market = {"US", "EU", "JP"};
  auto result = price_premium(pb, quality, mktcap, market);
  CHECK(result.n == 3);
  CHECK_FALSE(result.quality_coef.has_value());
}

// python3: price_premium on a 50-row fixture (np.random.seed(42)) ->
//   n=50, quality_coef=0.3826, quality_t=8.81, premium%=46.6, R2=0.689
TEST_CASE("price_premium matches Python's get_dummies-based fixed-effects regression",
          "[quality_factor]") {
  std::vector<double> pb = {
      2.2580195469, 1.9336350353, 3.1959805583, 3.9853944773, 1.4657683877, 2.3730245298,
      3.2525044876, 3.8063972033, 1.5677375242, 5.0582781763, 1.5848503170, 1.8398118016,
      3.3088036032, 0.7539572141, 1.3644779213, 3.0693856137, 1.0097897861, 3.0686275408,
      1.8761478318, 1.7225755624, 3.0945116859, 1.6081331283, 2.9510490284, 1.6189566098,
      1.9205372433, 2.9481551413, 1.2700763735, 3.0282806689, 2.1198316965, 1.6315236260,
      3.3543661746, 6.0336108932, 1.8154362968, 1.9215860299, 2.4701372593, 1.8733300815,
      3.9264676166, 0.8896539602, 1.8899455347, 3.0743991068, 4.2456196548, 4.8371756494,
      2.1213276199, 1.7165752748, 1.0263948829, 1.3617608885, 2.0227516550, 4.2023197482,
      3.0668748958, 1.5427328586};
  std::vector<double> quality = {
      0.4967141530,  -0.1382643012, 0.6476885381,  1.5230298564,  -0.2341533747, -0.2341369569,
      1.5792128155,  0.7674347292,  -0.4694743859, 0.5425600436,  -0.4634176928, -0.4657297536,
      0.2419622716,  -1.9132802447, -1.7249178325, -0.5622875292, -1.0128311203, 0.3142473326,
      -0.9080240755, -1.4123037013, 1.4656487689,  -0.2257763005, 0.0675282047,  -1.4247481862,
      -0.5443827245, 0.1109225897,  -1.1509935774, 0.3756980183,  -0.6006386899, -0.2916937498,
      -0.6017066122, 1.8522781845,  -0.0134972247, -1.0577109290, 0.8225449121,  -1.2208436500,
      0.2088635950,  -1.9596701239, -1.3281860489, 0.1968612359,  0.7384665800,  0.1713682812,
      -0.1156482824, -0.3011036956, -1.4785219904, -0.7198442084, -0.4606387710, 1.0571222262,
      0.3436182896,  -1.7630401554};
  std::vector<double> mktcap = {
      927652666.3968638182,  224600862.2183142304,  125291803.0822057426,  1648864288.1981284618,
      3814208634.8139367104, 3124562899.6269960403, 90563783.7786825597,   261403369.2437396944,
      941068851.0260030031,  3413794459.2371292114, 186073352.8898431659,  334678874.5669952035,
      53081023.6342970356,   44348380.5945850536,   2463999413.9887027740, 7309787621.5144338608,
      420090094.4527364373,  3610332808.5791687965, 1000006213.1681585312, 133519820.2116888016,
      999525486.6874839067,  10515047179.1323795319, 451618304.4145576954, 11089752399.8753700256,
      2572811.4074441558,    2510643693.3614315987, 577427895.6087694168,  266793444.0208311081,
      582897289.5534923077,  9109807.7952581141,    312669169.8930826783,  991000050.2726703882,
      9323352296.9274291992, 172078196.7020716667,  96303266.3053715229,   177856199.3316215575,
      3026898198.9136319160, 936352175.2826972008,  168168934.1363665462,  1354278756.0766065121,
      589128626.3629760742,  3367006747.2741856575, 119150006.0452265143,  251933496.2316930294,
      221466898.4760321081,  25983443.4752489813,   877195596.1347225904,  817785425.6785162687,
      490152396.1594755650,  303479837.5822690725};
  std::vector<std::string> market = {
      "US", "EU", "US", "US", "JP", "EU", "JP", "JP", "EU", "US", "US", "EU", "US", "EU", "EU",
      "JP", "EU", "JP", "US", "US", "US", "US", "JP", "US", "EU", "EU", "EU", "JP", "US", "US",
      "US", "JP", "EU", "EU", "US", "EU", "EU", "JP", "JP", "JP", "JP", "US", "JP", "EU", "US",
      "EU", "EU", "EU", "JP", "JP"};

  auto result = price_premium(pb, quality, mktcap, market);
  CHECK(result.n == 50);
  REQUIRE(result.quality_coef.has_value());
  CHECK(*result.quality_coef == Approx(0.3826).margin(1e-3));
  CHECK(*result.quality_t == Approx(8.81).margin(0.02));
  CHECK(*result.mb_premium_per_sd_pct == Approx(46.6).margin(0.1));
  CHECK(*result.r_squared == Approx(0.689).margin(0.002));
}
