// Golden values generated by running fx.py's actual functions.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include <fstream>
#include <filesystem>

#include "bazaartalks/quant_core/fx.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

TEST_CASE("market_currency is case-insensitive and defaults to USD", "[fx]") {
  CHECK(market_currency("kr") == "KRW");
  CHECK(market_currency("KR") == "KRW");
  CHECK(market_currency("XX") == "USD");  // unknown market code -> USD
}

TEST_CASE("convert_level and combine_return match Python", "[fx]") {
  CHECK(convert_level(1000, 0.00073) == Approx(0.73));
  CHECK(combine_return(0.02, -0.01) == Approx(0.009800000000000031));
}

TEST_CASE("load_rates_snapshot with base=USD returns the raw snapshot", "[fx]") {
  auto rates = load_rates_snapshot("USD");
  CHECK(rates.at("USD") == Approx(1.0));
  CHECK(rates.at("KRW") == Approx(0.00073));
}

// python3: load_rates(base='EUR') -- rebases the USD snapshot to EUR.
TEST_CASE("load_rates_snapshot rebases to a non-USD base and rounds to 6dp", "[fx]") {
  auto rates = load_rates_snapshot("EUR");
  CHECK(rates.at("KRW") == Approx(0.000676));
  CHECK(rates.at("JPY") == Approx(0.005926));
  CHECK(rates.at("EUR") == Approx(1.0));
}

TEST_CASE("load_rates_with_cache falls back to snapshot when the cache file is absent", "[fx]") {
  auto rates = load_rates_with_cache("/nonexistent/fx_rates.json", "USD");
  CHECK(rates.at("USD") == Approx(1.0));
  CHECK(rates.at("KRW") == Approx(0.00073));
}

TEST_CASE("load_rates_with_cache reads a matching-base cache file over the snapshot", "[fx]") {
  auto tmp = std::filesystem::temp_directory_path() / "bt_fx_test_rates.json";
  {
    std::ofstream f(tmp);
    f << R"({"base": "USD", "rates": {"USD": 1.0, "KRW": 0.00099}})";
  }
  auto rates = load_rates_with_cache(tmp.string(), "USD");
  CHECK(rates.at("KRW") == Approx(0.00099));  // cache value, NOT the 0.00073 snapshot value
  std::filesystem::remove(tmp);
}

TEST_CASE("load_rates_with_cache ignores a cache file for a different base", "[fx]") {
  auto tmp = std::filesystem::temp_directory_path() / "bt_fx_test_rates_wrongbase.json";
  {
    std::ofstream f(tmp);
    f << R"({"base": "EUR", "rates": {"EUR": 1.0}})";
  }
  auto rates = load_rates_with_cache(tmp.string(), "USD");  // cache is base=EUR, we asked for USD
  CHECK(rates.at("KRW") == Approx(0.00073));  // falls back to the USD snapshot
  std::filesystem::remove(tmp);
}
