// Golden values generated by running portfolio.py's actual optimizer
// functions on a fixed synthetic 5-asset return series (np.random.seed(9)).
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "bazaartalks/quant_core/portfolio.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
Matrix sample_cov() {
  Matrix cov(5, 5);
  cov << 0.022485194048521735, -0.0007040534109445277, 0.0011023491546203255,
      0.001895895125191855, -0.000557378637732307, -0.0007040534109445277, 0.028548961119313414,
      0.0009213405272252045, -0.0027156734385484316, 0.000803934315721694,
      0.0011023491546203255, 0.0009213405272252045, 0.028971901519597616, 0.0015949803002036785,
      0.004220162189652149, 0.001895895125191855, -0.0027156734385484316, 0.0015949803002036785,
      0.024728370539399448, -0.00026770811524436046, -0.000557378637732307, 0.000803934315721694,
      0.004220162189652149, -0.00026770811524436046, 0.026583036293274943;
  return cov;
}
Vector sample_mu() {
  Vector mu(5);
  mu << 0.12147918866716262, 0.1715924930462025, 0.17638906762874637, 0.0675045544401366,
      -0.13913461597592305;
  return mu;
}
}  // namespace

TEST_CASE("min_variance_weights matches Python's pinv-based formula", "[portfolio]") {
  Vector w = min_variance_weights(sample_cov());
  REQUIRE(w.size() == 5);
  CHECK(w(0) == Approx(0.23459583968653006));
  CHECK(w(1) == Approx(0.2134691584317603));
  CHECK(w(2) == Approx(0.13749518044516967));
  CHECK(w(3) == Approx(0.22498519240812637));
  CHECK(w(4) == Approx(0.18945462902841373));
  CHECK(w.sum() == Approx(1.0));
}

TEST_CASE("max_sharpe_weights matches Python's tangency-portfolio formula", "[portfolio]") {
  Vector w = max_sharpe_weights(sample_mu(), sample_cov());
  REQUIRE(w.size() == 5);
  CHECK(w(0) == Approx(0.3514390284279343));
  CHECK(w(1) == Approx(0.45405211370033766));
  CHECK(w(2) == Approx(0.46375218277400854));
  CHECK(w(3) == Approx(0.18347303433663434));
  CHECK(w(4) == Approx(-0.4527163592389148));
  CHECK(w.sum() == Approx(1.0));
}

TEST_CASE("long_only clips shorts to zero and renormalises", "[portfolio]") {
  Vector w(5);
  w << 0.5, -0.2, 0.3, -0.1, 0.5;
  Vector out = long_only(w);
  CHECK(out(0) == Approx(0.3846153846153846));
  CHECK(out(1) == Approx(0.0));
  CHECK(out(2) == Approx(0.23076923076923075));
  CHECK(out(3) == Approx(0.0));
  CHECK(out(4) == Approx(0.3846153846153846));
}

TEST_CASE("long_only falls back to equal-weight when every input is <= 0", "[portfolio]") {
  Vector w(3);
  w << -0.1, -0.2, -0.3;
  Vector out = long_only(w);
  CHECK(out(0) == Approx(1.0 / 3.0));
  CHECK(out(1) == Approx(1.0 / 3.0));
  CHECK(out(2) == Approx(1.0 / 3.0));
}

TEST_CASE("cap_weights enforces the per-position cap and matches Python", "[portfolio]") {
  Vector w(4);
  w << 0.5, 0.3, 0.1, 0.1;
  Vector out = cap_weights(w, 0.25);
  CHECK(out(0) == Approx(0.25));
  CHECK(out(1) == Approx(0.25));
  CHECK(out(2) == Approx(0.25));
  CHECK(out(3) == Approx(0.25));
}

TEST_CASE("cap_weights falls back to equal-weight when infeasible (cap*n < 1)", "[portfolio]") {
  Vector w(4);
  w << 0.7, 0.1, 0.1, 0.1;
  Vector out = cap_weights(w, 0.2);  // 0.2*4 = 0.8 < 1 -> infeasible
  for (Eigen::Index i = 0; i < 4; ++i) CHECK(out(i) == Approx(0.25));
}

// python3: apply_sector_cap([0.4,0.3,0.2,0.1], ['Tech','Tech','Health','Energy'], 0.35)
// -> [0.1999999999999999, 0.14999999999999994, 0.3500000000005897, 0.2999999999994104]
TEST_CASE("apply_sector_cap redistributes excess from an over-cap sector", "[portfolio]") {
  Vector w(4);
  w << 0.4, 0.3, 0.2, 0.1;
  std::vector<std::string> sectors = {"Tech", "Tech", "Health", "Energy"};
  Vector out = apply_sector_cap(w, sectors, 0.35);
  CHECK(out(0) == Approx(0.1999999999999999).margin(1e-6));
  CHECK(out(1) == Approx(0.14999999999999994).margin(1e-6));
  CHECK(out(2) == Approx(0.3500000000005897).margin(1e-6));
  CHECK(out(3) == Approx(0.2999999999994104).margin(1e-6));

  // Tech sector (indices 0,1) should now sum to <= 0.35 (the cap).
  CHECK(out(0) + out(1) <= Approx(0.35).margin(1e-6));
}

TEST_CASE("turnover and blend_to_turnover match Python", "[portfolio]") {
  Vector w_new(3), w_old(3);
  w_new << 0.5, 0.3, 0.2;
  w_old << 0.3, 0.3, 0.4;
  CHECK(turnover(w_new, w_old) == Approx(0.2));

  Vector blended = blend_to_turnover(w_new, w_old, 0.1);
  CHECK(blended(0) == Approx(0.4));
  CHECK(blended(1) == Approx(0.3));
  CHECK(blended(2) == Approx(0.30000000000000004));
}

TEST_CASE("blend_to_turnover returns w_new unchanged when already within budget",
          "[portfolio]") {
  Vector w_new(3), w_old(3);
  w_new << 0.5, 0.3, 0.2;
  w_old << 0.3, 0.3, 0.4;
  Vector blended = blend_to_turnover(w_new, w_old, 1.0);  // budget=1.0 >> actual turnover=0.2
  CHECK(blended(0) == Approx(0.5));
  CHECK(blended(1) == Approx(0.3));
  CHECK(blended(2) == Approx(0.2));
}
