// Golden values generated by running the ACTUAL dvm_global.py
// process_market() (unrounded, read directly out of its internal pandas
// Series before the module's own `.round()` calls -- see the commit
// message / PR description for the full generation script) against a
// 3-ticker, 220-bar synthetic OHLCV market. The three price paths are a
// closed-form trig/linear generator (not a random walk) so the exact same
// formula can be reproduced here in C++ instead of embedding thousands of
// literal floats -- both sides call the platform libm sin/cos, so the two
// should match to double precision.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/dvm_global.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {

constexpr std::size_t kN = 220;

std::vector<double> gen_close_tick0() {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 + 0.12 * di + 2.0 * std::sin(di * 1.047) + 3.0 * std::sin(di / 12.0);
    if (i >= 190) v += (di - 189.0) * 1.3;
    out[i] = v;
  }
  return out;
}

std::vector<double> gen_close_tick1() {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 - 0.05 * di + 2.0 * std::sin(di * 1.047 + 0.5) +
               2.5 * std::sin(di / 9.0 + 1.0);
    out[i] = v;
  }
  return out;
}

std::vector<double> gen_close_tick2() {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 + 0.03 * di + 2.0 * std::sin(di * 1.047 + 1.2) + 6.0 * std::sin(di / 12.0);
    if (i >= 150) v -= (di - 150.0) * 0.35;
    if (i >= 205) v += (di - 205.0) * 2.2;
    out[i] = v;
  }
  return out;
}

TickerSeries make_ticker(const std::string& name, const std::vector<double>& close,
                          double seedbase) {
  TickerSeries t;
  t.ticker = name;
  t.close = close;
  t.high.resize(kN);
  t.low.resize(kN);
  t.volume.resize(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    t.high[i] = close[i] + 0.3 + 0.2 * std::abs(std::sin(di * 0.7 + seedbase));
    t.low[i] = close[i] - 0.3 - 0.2 * std::abs(std::cos(di * 0.5 + seedbase));
    t.volume[i] = 2000.0 + 500.0 * std::sin(di * 0.3 + seedbase) + 1500.0;
  }
  return t;
}

std::vector<TickerSeries> make_market() {
  auto t0 = make_ticker("TICK0", gen_close_tick0(), 0.3);
  t0.volume.back() *= 3.0;  // volume thrust on the last bar
  auto t1 = make_ticker("TICK1", gen_close_tick1(), 1.7);
  auto t2 = make_ticker("TICK2", gen_close_tick2(), 2.9);
  return {t0, t1, t2};
}

const DvmGlobalMetrics& find(const std::vector<DvmGlobalMetrics>& rows, const std::string& t) {
  for (const auto& r : rows) {
    if (r.ticker == t) return r;
  }
  throw std::runtime_error("ticker not found: " + t);
}

}  // namespace

TEST_CASE("process_market matches dvm_global.py's unrounded snapshot", "[dvm_global]") {
  auto rows = process_market("TEST5", make_market());
  REQUIRE(rows.size() == 3);

  const auto& t0 = find(rows, "TICK0");
  CHECK(t0.M == Approx(86.6614782087).epsilon(1e-6));
  CHECK(t0.rsi == Approx(94.9544497571).epsilon(1e-6));
  CHECK(t0.mfi == Approx(56.9163411203).epsilon(1e-6));
  CHECK(t0.adx == Approx(85.9746224973).epsilon(1e-6));
  CHECK(t0.dist_52w == Approx(-0.0407437446).margin(1e-6));
  CHECK(t0.vol_ratio == Approx(2.7126602082).epsilon(1e-6));
  CHECK(t0.beta == Approx(0.8262523525).epsilon(1e-5));
  CHECK(t0.above_200dma == true);
  CHECK(t0.golden_cross == false);
  CHECK(t0.sma50_above_200 == true);
  CHECK(t0.macd_bull == true);

  const auto& t1 = find(rows, "TICK1");
  CHECK(t1.M == Approx(49.0040717795).epsilon(1e-6));
  CHECK(t1.rsi == Approx(48.2965912874).epsilon(1e-6));
  CHECK(t1.mfi == Approx(43.2351098923).epsilon(1e-6));
  CHECK(t1.adx == Approx(13.8898642283).epsilon(1e-6));
  CHECK(t1.dist_52w == Approx(-14.8995542993).epsilon(1e-6));
  CHECK(t1.vol_ratio == Approx(0.8529354766).epsilon(1e-6));
  CHECK(t1.beta == Approx(1.1560183746).epsilon(1e-5));
  CHECK(t1.above_200dma == false);
  CHECK(t1.golden_cross == false);
  CHECK(t1.sma50_above_200 == false);
  CHECK(t1.macd_bull == true);

  const auto& t2 = find(rows, "TICK2");
  CHECK(t2.M == Approx(68.2374572966).epsilon(1e-6));
  CHECK(t2.rsi == Approx(99.8845437521).epsilon(1e-6));
  CHECK(t2.mfi == Approx(92.6675785283).epsilon(1e-6));
  CHECK(t2.adx == Approx(58.7886531159).epsilon(1e-6));
  CHECK(t2.dist_52w == Approx(-2.4061506944).epsilon(1e-6));
  CHECK(t2.vol_ratio == Approx(0.9282456673).epsilon(1e-6));
  CHECK(t2.beta == Approx(1.0027292729).epsilon(1e-5));
  CHECK(t2.above_200dma == true);
  CHECK(t2.golden_cross == false);
  CHECK(t2.sma50_above_200 == false);
  CHECK(t2.macd_bull == true);
}

TEST_CASE("process_market screens match dvm_global.py's SCREENS dict", "[dvm_global]") {
  auto rows = process_market("TEST5", make_market());
  const auto& t0 = find(rows, "TICK0");
  const auto& t1 = find(rows, "TICK1");
  const auto& t2 = find(rows, "TICK2");

  // python3: momentum_breakout hits -> ['TICK0']
  CHECK(screen_momentum_breakout(t0) == true);
  CHECK(screen_momentum_breakout(t1) == false);
  CHECK(screen_momentum_breakout(t2) == false);

  // python3: high_momentum hits -> ['TICK0']
  CHECK(screen_high_momentum(t0) == true);
  CHECK(screen_high_momentum(t1) == false);
  CHECK(screen_high_momentum(t2) == false);

  // python3: golden_crossover hits -> [] (no ticker crosses in this fixture)
  CHECK(screen_golden_crossover(t0) == false);
  CHECK(screen_golden_crossover(t1) == false);
  CHECK(screen_golden_crossover(t2) == false);

  // python3: uptrend_quality hits -> []
  CHECK(screen_uptrend_quality(t0) == false);
  CHECK(screen_uptrend_quality(t1) == false);
  CHECK(screen_uptrend_quality(t2) == false);

  // python3: trendlyne_technical hits -> []
  CHECK(screen_trendlyne_technical(t0) == false);
  CHECK(screen_trendlyne_technical(t1) == false);
  CHECK(screen_trendlyne_technical(t2) == false);

  // python3: sma_golden hits -> ['TICK0']
  CHECK(screen_sma_golden(t0) == true);
  CHECK(screen_sma_golden(t1) == false);
  CHECK(screen_sma_golden(t2) == false);
}

TEST_CASE("process_market excludes tickers below min_bars, matching c.count() >= MIN_BARS",
          "[dvm_global]") {
  auto tickers = make_market();
  // A 4th ticker with only 50 bars -- below the default MIN_BARS=200 --
  // must be excluded from the result entirely, not scored with partial data.
  TickerSeries shorthist;
  shorthist.ticker = "SHORTHIST";
  for (int i = 0; i < 50; ++i) {
    double di = static_cast<double>(i);
    shorthist.close.push_back(50.0 + std::sin(di / 5.0));
  }
  shorthist.high = shorthist.close;
  shorthist.low = shorthist.close;
  shorthist.volume.assign(50, 1000.0);
  // Pad to the shared date-index length with leading NaN, matching pandas'
  // pivot NaN-fill for a ticker not listed on the market's earliest dates.
  TickerSeries padded;
  padded.ticker = "SHORTHIST";
  padded.close.assign(kN - 50, std::nan(""));
  padded.close.insert(padded.close.end(), shorthist.close.begin(), shorthist.close.end());
  padded.high = padded.close;
  padded.low = padded.close;
  padded.volume.assign(kN - 50, std::nan(""));
  padded.volume.insert(padded.volume.end(), shorthist.volume.begin(), shorthist.volume.end());
  tickers.push_back(padded);

  auto rows = process_market("TEST5", tickers);
  REQUIRE(rows.size() == 3);
  for (const auto& r : rows) CHECK(r.ticker != "SHORTHIST");
}

TEST_CASE("golden_cross fires on a genuine one-bar-back 50/200-DMA crossover", "[dvm_global]") {
  // Hand-crafted case isolating just the golden_cross bit, independent of
  // the big fixture above (which never crosses): a flat close series with
  // a slope change on the very last bar. A 50-bar SMA reacts to a slope
  // change immediately (its window shifts entirely onto the new slope in
  // one step), while a 200-bar SMA barely moves -- verified in Python that
  // the crossover always lands exactly on the bar the slope changes, so
  // putting that change on the final bar is what's needed to make
  // process_market()'s `.iloc[-1]`-only check observe `golden_cross=True`.
  TickerSeries t;
  t.ticker = "CROSS";
  std::size_t n = 260;
  std::size_t rally_start = n - 1;
  t.close.resize(n);
  for (std::size_t i = 0; i < n; ++i) {
    double v = 100.0;
    if (i >= rally_start) v += static_cast<double>(i - rally_start + 1) * 3.0;
    t.close[i] = v;
  }
  t.high = t.close;
  t.low = t.close;
  t.volume.assign(n, 1000.0);
  for (auto& v : t.high) v += 0.1;
  for (auto& v : t.low) v -= 0.1;

  auto rows = process_market("X", {t});
  REQUIRE(rows.size() == 1);
  CHECK(rows[0].golden_cross == true);
}
