// Golden values generated by running crowding.py's actual functions
// (np.random.seed(3), n=80 daily returns with the stock a noisy 0.7-beta
// combination of the market proxy).
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/crowding.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
const std::vector<double> kStockRet = {
    0.00450639,  0.00469695,  0.00456994,  -0.01786192, -0.00086134, 0.00473398,  -0.00051382,
    -0.00951095, -0.01759115, -0.00896157, -0.01253353, 0.00330385,  0.00061925,  0.01444078,
    -0.00288802, -0.00327947, 0.00046691,  -0.01574796, 0.00528534,  0.00545142,  -0.00283961,
    -0.00899077, 0.01013459,  0.00525393,  0.00044433,  -0.00388703, 0.00140322,  -0.00529675,
    -0.00130148, 0.00047815,  0.00232551,  0.01290835,  -0.01099605, 0.00017303,  -0.00955613,
    -0.01380510, -0.00114743, -0.00403963, 0.00307241,  0.00735656,  -0.01522227, 0.00729534,
    -0.00680390, -0.02245665, -0.00261205, -0.00218795, -0.00637182, 0.00207441,  -0.01941827,
    -0.00608912, 0.00629374,  0.01763525,  0.01285620,  0.00492578,  0.01397508,  -0.01048829,
    0.00338727,  -0.00766052, -0.00716178, -0.02324511, 0.00210806,  0.01007666,  -0.00040386,
    0.02008221,  -0.00880925, 0.00565311,  0.00383642,  -0.00813345, 0.00829069,  0.01673556,
    -0.01213837, 0.01293547,  -0.00819696, 0.01295508,  0.00361118,  0.00749133,  0.00035954,
    0.00174395,  -0.01040406, 0.01593417};

const std::vector<double> kMktRet = {
    0.01818628,  0.00466510,  0.00126497,  -0.01833493, -0.00247388, -0.00324759, -0.00052741,
    -0.00597001, -0.00013818, -0.00447218, -0.01283865, 0.00914622,  0.00911318,  0.01739573,
    0.00080034,  -0.00374677, -0.00515360, -0.01516477, 0.01012367,  -0.01071068, -0.01155047,
    -0.00175650, 0.01516148,  0.00266716,  -0.00993785, -0.00682993, 0.00655245,  -0.00130513,
    -0.00738836, -0.00200031, 0.00775056,  0.02006111,  -0.01214123, -0.00596417, -0.00773766,
    -0.02389083, -0.00893792, -0.00993876, 0.01153978,  -0.00101914, -0.01593285, 0.00676675,
    -0.00326271, -0.01713141, -0.00566650, -0.00558594, -0.00843882, 0.00059714,  -0.02218258,
    -0.00237762, 0.01043183,  0.00882798,  0.01138187,  0.01149391,  0.01517543,  -0.01088301,
    0.00875833,  -0.01830890, -0.00572885, -0.01884472, 0.01078148,  0.01363738,  -0.00167415,
    0.01804645,  -0.00644728, 0.00180617,  0.00182946,  -0.01034195, 0.00467947,  0.01968978,
    -0.00994931, 0.00929338,  -0.00124507, 0.01799627,  0.00513788,  0.00706216,  0.00673163,
    0.00279087,  -0.01365764, 0.01421663};
}  // namespace

TEST_CASE("corr_to_market matches Python on a synthetic 0.7-beta series", "[crowding]") {
  CHECK(corr_to_market(kStockRet, kMktRet) == Approx(0.8499192553679926));
}

TEST_CASE("corr_to_market returns NaN with fewer than 20 paired observations", "[crowding]") {
  std::vector<double> a(10, 0.01), b(10, 0.01);
  CHECK(std::isnan(corr_to_market(a, b)));
}

// python3: rel_strength(prices, 63) on cumprod(1+stock_ret) starting at 100 -> 0.001964851527747724
TEST_CASE("rel_strength matches Python's trailing-window return", "[crowding]") {
  std::vector<double> prices(kStockRet.size());
  double cum = 100.0;
  for (std::size_t i = 0; i < kStockRet.size(); ++i) {
    cum *= (1.0 + kStockRet[i]);
    prices[i] = cum;
  }
  // Wider epsilon than other golden checks: kStockRet is printed to 8
  // decimal places, and compounding 80 truncated returns via cumprod
  // amplifies that truncation into ~1e-5 relative drift by the end of
  // the series -- corr_to_market() on this same truncated array matches
  // Python to 1e-13, confirming the algorithm itself is exact and this
  // is a fixture-precision artifact, not a logic bug.
  CHECK(rel_strength(prices, 63) == Approx(0.001964851527747724).epsilon(1e-4));
}

TEST_CASE("rel_strength returns NaN with insufficient history", "[crowding]") {
  std::vector<double> prices = {100, 101, 102};
  CHECK(std::isnan(rel_strength(prices, 63)));
}

// python3: crowding_score on feat = corr_mkt=[0.9,0.5,0.2,0.7,-0.1], rel_strength=[0.3,0.1,-0.2,0.05,0.5]
// -> [93.0, 60.0, 33.0, 66.0, 48.0]
TEST_CASE("crowding_score matches Python's percentile-rank composite", "[crowding]") {
  std::vector<CrowdingFeatures> feat = {
      {0.9, 0.3}, {0.5, 0.1}, {0.2, -0.2}, {0.7, 0.05}, {-0.1, 0.5},
  };
  auto scores = crowding_score(feat);
  REQUIRE(scores.size() == 5);
  CHECK(scores[0] == Approx(93.0));
  CHECK(scores[1] == Approx(60.0));
  CHECK(scores[2] == Approx(33.0));
  CHECK(scores[3] == Approx(66.0));
  CHECK(scores[4] == Approx(48.0));
}
