// Golden values generated by running unlisted_valuation.py's actual
// functions on a fixed peer-multiple list.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <limits>

#include "bazaartalks/quant_core/unlisted_valuation.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
constexpr double kNaN = std::numeric_limits<double>::quiet_NaN();
}

// python3: peer_multiple_band([15.2,18.5,-3.0,nan,22.1,12.8,19.9,25.0,14.0])
// -> {'n': 7, 'median': 18.5, 'q1': 14.6, 'q3': 21.0}  (drops the -3.0 and NaN)
TEST_CASE("peer_multiple_band drops non-positive/non-finite values and matches Python",
          "[unlisted_valuation]") {
  std::vector<double> multiples = {15.2, 18.5, -3.0, kNaN, 22.1, 12.8, 19.9, 25.0, 14.0};
  auto band = peer_multiple_band(multiples);
  REQUIRE(band.n == 7);
  REQUIRE(band.median.has_value());
  CHECK(*band.median == Approx(18.5));
  CHECK(*band.q1 == Approx(14.6));
  CHECK(*band.q3 == Approx(21.0));
}

TEST_CASE("peer_multiple_band returns an empty band when nothing survives the filter",
          "[unlisted_valuation]") {
  auto band = peer_multiple_band({-1.0, kNaN, 0.0});
  CHECK(band.n == 0);
  CHECK_FALSE(band.median.has_value());
  CHECK_FALSE(band.q1.has_value());
  CHECK_FALSE(band.q3.has_value());
}

// python3: value_range(5e7, band) -> low=730000000.0 mid=925000000.0 high=1050000000.0, n_peers=7
TEST_CASE("value_range applies the band to a metric and matches Python", "[unlisted_valuation]") {
  std::vector<double> multiples = {15.2, 18.5, -3.0, kNaN, 22.1, 12.8, 19.9, 25.0, 14.0};
  auto band = peer_multiple_band(multiples);
  auto vr = value_range(5e7, band);
  REQUIRE(vr.low.has_value());
  CHECK(*vr.low == Approx(730000000.0));
  CHECK(*vr.mid == Approx(925000000.0));
  CHECK(*vr.high == Approx(1050000000.0));
  CHECK(vr.n_peers == 7);
}

TEST_CASE("value_range with no peer coverage returns an all-empty range",
          "[unlisted_valuation]") {
  MultipleBand empty_band;
  auto vr = value_range(5e7, empty_band);
  CHECK_FALSE(vr.low.has_value());
  CHECK_FALSE(vr.mid.has_value());
  CHECK_FALSE(vr.high.has_value());
  CHECK(vr.n_peers == 0);
}
