// Golden tests generated by running pit_panel.py's actual functions on the
// exact panel fixture from its own main().
#include <catch2/catch_test_macros.hpp>

#include "bazaartalks/quant_core/pit_panel.hpp"

using namespace bazaartalks::quant_core;
using date::day;
using date::month;
using date::year;

namespace {
date::year_month_day ymd(int y, unsigned m, unsigned d) { return year{y} / month{m} / day{d}; }

std::vector<FiledRecord> sample_panel() {
  return {
      {"AAA", ymd(2023, 2, 10)},
      {"AAA", ymd(2024, 2, 12)},
      {"AAA", ymd(2025, 2, 11)},  // future vs. the 2024-06-30 asof used below
      {"BBB", ymd(2024, 5, 1)},
  };
}
}  // namespace

// python3: as_of(panel, "2024-06-30") -> {'AAA': index 1 (2024-02-12 filing),
// 'BBB': index 3} -- AAA must NOT use the 2025 filing (no look-ahead).
TEST_CASE("as_of picks the latest filing on/before asof, never a future one", "[pit_panel]") {
  auto panel = sample_panel();
  auto picked = as_of(panel, ymd(2024, 6, 30));
  REQUIRE(picked.count("AAA") == 1);
  REQUIRE(picked.count("BBB") == 1);
  CHECK(picked.at("AAA") == 1);  // the 2024-02-12 filing, not the 2025 one
  CHECK(picked.at("BBB") == 3);
}

TEST_CASE("leaks_lookahead is true when the panel contains a future-filed row", "[pit_panel]") {
  auto panel = sample_panel();
  CHECK(leaks_lookahead(panel, ymd(2024, 6, 30)) == true);   // AAA's 2025 row leaks
  CHECK(leaks_lookahead(panel, ymd(2025, 3, 1)) == false);   // now every row is <= asof
}

// python3: gate_markets({'US':2520,'BR':900,'JP':240,'CN':180}, min_years=3.0)
// -> report=['BR','US'], withhold=['CN','JP']
TEST_CASE("gate_markets splits by the 3-year history bar and sorts market names",
          "[pit_panel]") {
  std::unordered_map<std::string, int> hist = {{"US", 2520}, {"BR", 900}, {"JP", 240}, {"CN", 180}};
  auto gate = gate_markets(hist, 3.0);
  CHECK(gate.report == std::vector<std::string>{"BR", "US"});
  CHECK(gate.withhold == std::vector<std::string>{"CN", "JP"});
  CHECK(gate.min_days == 756);  // 3.0 * 252
}

TEST_CASE("min_history_ok matches the trading-days-per-year threshold", "[pit_panel]") {
  CHECK(min_history_ok(756, 3.0) == true);
  CHECK(min_history_ok(755, 3.0) == false);
}
