// Golden tests generated by running survivorship.py's actual functions on
// the exact membership fixture from its own main().
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/survivorship.hpp"

using namespace bazaartalks::quant_core;
using date::day;
using date::month;
using date::year;
using Catch::Approx;

namespace {
date::year_month_day ymd(int y, unsigned m, unsigned d) { return year{y} / month{m} / day{d}; }

std::vector<MembershipRecord> sample_membership() {
  return {
      {"ALIVE1", ymd(2015, 1, 1), std::nullopt},
      {"ALIVE2", ymd(2018, 6, 1), std::nullopt},
      {"DIED", ymd(2015, 1, 1), ymd(2020, 3, 15)},
      {"FUTURE", ymd(2024, 1, 1), std::nullopt},
  };
}
}  // namespace

// python3: point_in_time_universe(membership, asof) for each asof below.
TEST_CASE("point_in_time_universe matches Python across four asof dates", "[survivorship]") {
  auto m = sample_membership();

  CHECK(point_in_time_universe(m, ymd(2016, 1, 1)) ==
        std::vector<std::string>{"ALIVE1", "DIED"});
  CHECK(point_in_time_universe(m, ymd(2019, 1, 1)) ==
        std::vector<std::string>{"ALIVE1", "ALIVE2", "DIED"});
  CHECK(point_in_time_universe(m, ymd(2021, 1, 1)) ==
        std::vector<std::string>{"ALIVE1", "ALIVE2"});
  CHECK(point_in_time_universe(m, ymd(2025, 1, 1)) ==
        std::vector<std::string>{"ALIVE1", "ALIVE2", "FUTURE"});
}

TEST_CASE("apply_delisting_returns splices the delisting-day return then blanks afterward",
          "[survivorship]") {
  ReturnsPanel panel;
  panel.dates = {ymd(2020, 3, 13), ymd(2020, 3, 15), ymd(2020, 3, 16), ymd(2020, 3, 17)};
  panel.symbols = {"DIED", "ALIVE1"};
  panel.values = {
      {0.01, 0.02},
      {0.005, 0.01},   // this row IS the delisting date -> DIED gets spliced
      {0.03, -0.01},   // after delisting -> DIED goes NaN
      {-0.02, 0.015},  // after delisting -> DIED stays NaN
  };

  std::vector<std::pair<std::string, DelistingInfo>> delistings = {
      {"DIED", DelistingInfo{ymd(2020, 3, 15), -0.80}},  // bankruptcy-style final return
  };

  auto out = apply_delisting_returns(panel, delistings);

  CHECK(out.values[0][0] == Approx(0.01));           // before delisting date: unchanged
  CHECK(out.values[1][0] == Approx(-0.80));          // ON delisting date: spliced
  CHECK(std::isnan(out.values[2][0]));               // after: blanked
  CHECK(std::isnan(out.values[3][0]));               // after: blanked
  CHECK(out.values[0][1] == Approx(0.02));           // ALIVE1 untouched throughout
  CHECK(out.values[3][1] == Approx(0.015));

  // apply_delisting_returns returns a NEW panel -- input must be untouched.
  CHECK(panel.values[1][0] == Approx(0.005));
  CHECK(panel.values[2][0] == Approx(0.03));
}

TEST_CASE("survivorship_gap is survivors-only minus full-universe mean", "[survivorship]") {
  CHECK(survivorship_gap(0.05, 0.09) == Approx(0.04));
}
