// Golden values for the main fixture generated by running the ACTUAL
// screen_viability.py screens_for()/eval_ticker() against a closed-form
// (trig/linear, not random) 320-bar synthetic OHLCV series -- same
// generator-formula approach as libs/quant_core/dvm_global's tests, so
// the formula is reproducible here instead of embedding literal arrays.
// See the commit message / PR description for the generation script.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/screen_viability.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {

constexpr std::size_t kN = 320;

std::vector<double> gen_close(double seedbase, double trendslope, double wobble_amp,
                              double wobble_period, int rally_start = -1,
                              double rally_slope = 0.0) {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 + trendslope * di + wobble_amp * std::sin(di / wobble_period + seedbase);
    if (rally_start >= 0 && static_cast<int>(i) >= rally_start) {
      v += static_cast<double>(static_cast<int>(i) - rally_start + 1) * rally_slope;
    }
    out[i] = v;
  }
  return out;
}

struct Ohlcv {
  std::vector<double> close, high, low, volume;
};

Ohlcv build_ohlcv(const std::vector<double>& close, double seedbase) {
  Ohlcv o;
  o.close = close;
  o.high.resize(kN);
  o.low.resize(kN);
  o.volume.resize(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    o.high[i] = close[i] + 0.3 + 0.2 * std::abs(std::sin(di * 0.7 + seedbase));
    o.low[i] = close[i] - 0.3 - 0.2 * std::abs(std::cos(di * 0.5 + seedbase));
    o.volume[i] = 2000.0 + 500.0 * std::sin(di * 0.3 + seedbase) + 1500.0;
  }
  return o;
}

const ScreenEvalRow& find(const std::vector<ScreenEvalRow>& rows, const std::string& name) {
  for (const auto& r : rows) {
    if (r.screen == name) return r;
  }
  throw std::runtime_error("screen not found: " + name);
}

}  // namespace

TEST_CASE("screens_for + eval_ticker match screen_viability.py on the main fixture",
          "[screen_viability]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0, /*rally_start=*/290, /*rally_slope=*/1.3);
  auto o = build_ohlcv(close, 0.3);
  o.volume.back() *= 8.0;  // volume thrust near the end

  auto sig = screens_for(o.close, o.high, o.low, o.volume);
  int rsi_true = 0, near52_true = 0, pvb_true = 0, darvas_true = 0, gc_true = 0;
  for (std::size_t i = 0; i < kN; ++i) {
    rsi_true += sig.rsi_oversold[i];
    near52_true += sig.near_52w_high[i];
    pvb_true += sig.price_vol_breakout[i];
    darvas_true += sig.darvas_proximity[i];
    gc_true += sig.golden_crossover[i];
  }
  CHECK(rsi_true == 88);
  CHECK(near52_true == 201);
  CHECK(pvb_true == 1);
  CHECK(darvas_true == 0);
  CHECK(gc_true == 0);
  CHECK(sig.price_vol_breakout.back() == true);

  auto rows = eval_ticker(o.close, o.high, o.low, o.volume, /*horizon=*/5, /*clip=*/30.0);
  REQUIRE(rows.size() == 5);

  const auto& rsi_row = find(rows, "rsi_oversold");
  CHECK(rsi_row.n_signals == 88);
  CHECK(rsi_row.avg_fwd == Approx(-0.1285));
  CHECK(rsi_row.hit_pct == Approx(35.2));
  CHECK(rsi_row.baseline == Approx(0.9006));
  CHECK(rsi_row.edge == Approx(-1.0291));

  const auto& near52_row = find(rows, "near_52w_high");
  CHECK(near52_row.n_signals == 196);  // 201 signal days minus the last 5 (fwd undefined there)
  CHECK(near52_row.avg_fwd == Approx(1.194));
  CHECK(near52_row.hit_pct == Approx(73.0));
  CHECK(near52_row.edge == Approx(0.2933));

  for (const char* name : {"price_vol_breakout", "darvas_proximity", "golden_crossover"}) {
    const auto& row = find(rows, name);
    CHECK(row.n_signals == 0);
    CHECK(std::isnan(row.avg_fwd));
    CHECK(std::isnan(row.hit_pct));
    CHECK(std::isnan(row.edge));
    CHECK(row.baseline == Approx(0.9006));
  }
}

TEST_CASE("eval_ticker returns empty below the MIN_BARS+horizon minimum", "[screen_viability]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0);
  close.resize(304);  // 300 (default min_bars) + 5 (default horizon) - 1
  auto o = build_ohlcv(close, 0.3);
  auto rows = eval_ticker(o.close, o.high, o.low, o.volume);
  CHECK(rows.empty());
}

TEST_CASE("darvas_proximity fires when close is near its 52w high and well above its 52w low",
          "[screen_viability]") {
  // python3 cross-check: a low-then-flat-high close series (52w low ~50.9,
  // 52w high == last close == 100) with vol > 1e5 throughout -> True.
  constexpr std::size_t n = 270;
  std::vector<double> close(n), high(n), low(n), volume(n, 2e5);
  for (std::size_t i = 0; i < n; ++i) {
    close[i] = (i < 130) ? (50.0 + static_cast<double>(i) * 0.05) : 100.0;
    high[i] = close[i] + 0.1;
    low[i] = close[i] - 0.1;
  }
  auto sig = screens_for(close, high, low, volume);
  CHECK(sig.darvas_proximity.back() == true);
  int count = 0;
  for (bool v : sig.darvas_proximity) count += v;
  CHECK(count == 151);
}

TEST_CASE("golden_crossover fires on a genuine one-bar-back 50/200-DMA crossover",
          "[screen_viability]") {
  // Same construction as dvm_global's golden_cross test: a flat close
  // series with the slope change landing exactly on the final bar, since
  // a 50-bar SMA reacts to a slope change immediately while a 200-bar SMA
  // barely moves.
  constexpr std::size_t n = 260;
  std::size_t rally_start = n - 1;
  std::vector<double> close(n);
  for (std::size_t i = 0; i < n; ++i) {
    double v = 100.0;
    if (i >= rally_start) v += static_cast<double>(i - rally_start + 1) * 3.0;
    close[i] = v;
  }
  std::vector<double> high(n), low(n), volume(n, 1000.0);
  for (std::size_t i = 0; i < n; ++i) {
    high[i] = close[i] + 0.1;
    low[i] = close[i] - 0.1;
  }
  auto sig = screens_for(close, high, low, volume);
  CHECK(sig.golden_crossover.back() == true);
  int count = 0;
  for (bool v : sig.golden_crossover) count += v;
  CHECK(count == 1);
}

TEST_CASE("aggregate_market_screen_summary matches write_summary()'s GROUP BY/AVG SQL",
          "[screen_viability]") {
  std::vector<TickerScreenRow> rows = {
      {"US", "AAA", "rsi_oversold", 10, 1.0, 60.0, 0.5},
      {"US", "BBB", "rsi_oversold", 5, -1.0, 40.0, -1.5},
      {"US", "CCC", "rsi_oversold", 0, 0.0, 0.0, 0.0},   // n_signals==0 -> excluded entirely
      {"JP", "DDD", "rsi_oversold", 8, 2.0, 70.0, 1.0},
  };
  auto summary = aggregate_market_screen_summary(rows);
  REQUIRE(summary.size() == 2);

  // US: avg over AAA+BBB only (CCC excluded by n_signals==0):
  // avg_fwd=(1.0-1.0)/2=0.0, avg_hit=(60+40)/2=50.0, avg_edge=(0.5-1.5)/2=-0.5
  // total_signals=15, n_tickers=2, pct_pos_edge = 1/2*100=50.0
  // viable: avg_edge(-0.5)>0 is False -> "no"
  const auto& us = summary[0].market == "US" ? summary[0] : summary[1];
  CHECK(us.market == "US");
  CHECK(us.n_tickers == 2);
  CHECK(us.total_signals == 15);
  CHECK(us.avg_fwd5d == Approx(0.0));
  CHECK(us.avg_hit_pct == Approx(50.0));
  CHECK(us.avg_edge == Approx(-0.5));
  CHECK(us.pct_tickers_pos_edge == Approx(50.0));
  CHECK(us.viable == "no");

  const auto& jp = summary[0].market == "JP" ? summary[0] : summary[1];
  CHECK(jp.market == "JP");
  CHECK(jp.n_tickers == 1);
  CHECK(jp.total_signals == 8);
  CHECK(jp.avg_edge == Approx(1.0));
  CHECK(jp.avg_hit_pct == Approx(70.0));
  // viable: avg_edge(1.0)>0 AND avg_hit_pct(70)>50 -> "YES"
  CHECK(jp.viable == "YES");

  // ORDER BY market ASC -> JP before US
  CHECK(summary[0].market == "JP");
  CHECK(summary[1].market == "US");
}

TEST_CASE("aggregate_market_screen_summary sorts by avg_edge DESC within a market",
          "[screen_viability]") {
  std::vector<TickerScreenRow> rows = {
      {"US", "AAA", "rsi_oversold", 10, 0.0, 0.0, -1.0},
      {"US", "BBB", "near_52w_high", 10, 0.0, 0.0, 2.0},
      {"US", "CCC", "golden_crossover", 10, 0.0, 0.0, 0.5},
  };
  auto summary = aggregate_market_screen_summary(rows);
  REQUIRE(summary.size() == 3);
  CHECK(summary[0].screen == "near_52w_high");     // edge 2.0
  CHECK(summary[1].screen == "golden_crossover");  // edge 0.5
  CHECK(summary[2].screen == "rsi_oversold");      // edge -1.0
}
