// Golden values for run_market() generated by directly re-executing
// pit_global.py's run_market() loop logic (the actual Python source lines,
// not a hand reimplementation) against a synthetic 3-ticker fixture --
// see the commit message / PR description for the full script. Uses the
// same AAA/BBB two-ticker date fixture as pit_backtest's tests, plus a
// third ticker CCC (full history like AAA, also a breakout, but NOT in
// the durable set) specifically so A_darvas and D_darvas_durable produce
// genuinely different results -- with only AAA/BBB, both arms happened
// to coincide, which wouldn't have caught a bug that mixed them up.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/pit_global.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {

date::sys_days d(int y, unsigned m, unsigned dd) {
  return date::sys_days{date::year{y} / m / dd};
}

std::vector<TickerHistory> make_fixture() {
  TickerHistory aaa;
  aaa.ticker = "AAA";
  {
    date::sys_days start = d(2024, 1, 1), end = d(2024, 4, 10);
    int i = 0;
    for (date::sys_days t = start; t <= end; t += date::days{1}, ++i) {
      aaa.dates.push_back(t);
      aaa.close.push_back(100.0 + static_cast<double>(i));
    }
  }

  TickerHistory bbb;
  bbb.ticker = "BBB";
  {
    date::sys_days start = d(2024, 2, 15), end = d(2024, 4, 10);
    int i = 0;
    for (date::sys_days t = start; t <= end; t += date::days{1}, ++i) {
      bbb.dates.push_back(t);
      bbb.close.push_back(50.0 + static_cast<double>(i));
    }
  }

  TickerHistory ccc;
  ccc.ticker = "CCC";
  {
    date::sys_days start = d(2024, 1, 1), end = d(2024, 4, 10);
    int i = 0;
    for (date::sys_days t = start; t <= end; t += date::days{1}, ++i) {
      ccc.dates.push_back(t);
      ccc.close.push_back(200.0 + 1.5 * static_cast<double>(i));
    }
  }

  return {aaa, bbb, ccc};
}

const MarketArmResult& find(const std::vector<MarketArmResult>& rows, const std::string& arm) {
  for (const auto& r : rows) {
    if (r.arm == arm) return r;
  }
  throw std::runtime_error("arm not found: " + arm);
}

}  // namespace

TEST_CASE("market_cost matches apply_costs.py's COSTS_PCT via COST_BUCKET indirection",
          "[pit_global]") {
  CHECK(market_cost("US") == Approx(0.10));
  CHECK(market_cost("JP") == Approx(0.20));   // via COST_BUCKET["JP"]="Japan"
  CHECK(market_cost("KR") == Approx(0.25));
  CHECK(market_cost("DE") == Approx(0.40));   // via COST_BUCKET["DE"]="Europe"
  CHECK(market_cost("UK") == Approx(0.40));   // via COST_BUCKET["UK"]="Europe"
  CHECK(market_cost("ZZ") == Approx(0.30));   // unknown market -> fallback
}

TEST_CASE("is_durable matches roe>12 and de<1.5, NaN-safe", "[pit_global]") {
  CHECK(is_durable(15.0, 1.0) == true);
  CHECK(is_durable(12.0, 1.0) == false);   // roe not strictly > 12
  CHECK(is_durable(15.0, 1.5) == false);   // de not strictly < 1.5
  CHECK(is_durable(std::nan(""), 1.0) == false);
  CHECK(is_durable(15.0, std::nan("")) == false);
}

TEST_CASE("base_symbol_upper strips the exchange suffix and uppercases", "[pit_global]") {
  CHECK(base_symbol_upper("7203.T") == "7203");
  CHECK(base_symbol_upper("infy.ns") == "INFY");
  CHECK(base_symbol_upper("AAPL") == "AAPL");
}

TEST_CASE("run_market returns empty for a universe below the 20-ticker minimum",
          "[pit_global]") {
  auto tickers = make_fixture();  // only 3 tickers
  auto rows = run_market("US", tickers, /*overlay=*/false);
  CHECK(rows.empty());
}

TEST_CASE("run_market matches pit_global.py's run_market() loop, including the "
          "overlay's exact ticker-inclusion divergence from the plain Darvas arm",
          "[pit_global]") {
  // Pad the fixture to >=20 tickers with additional never-listed-long-enough
  // filler tickers so only the 20-ticker MINIMUM guard is satisfied without
  // perturbing the arm math -- each filler has too little history (10 bars)
  // to ever produce a valid period_return, so it contributes nothing.
  auto tickers = make_fixture();
  for (int k = 0; k < 20; ++k) {
    TickerHistory filler;
    filler.ticker = "FILLER" + std::to_string(k);
    date::sys_days start = d(2024, 4, 1);
    for (int i = 0; i < 5; ++i) {
      filler.dates.push_back(start + date::days{i});
      filler.close.push_back(10.0);
    }
    tickers.push_back(filler);
  }

  std::set<std::string> durable = {"AAA"};
  auto rows = run_market("US", tickers, /*overlay=*/true, durable, /*darvas_lookback=*/20,
                         /*min_lookback=*/20);
  REQUIRE(rows.size() == 3);

  const auto& a = find(rows, "A_darvas");
  CHECK(a.metrics.n_months == 2);
  CHECK(a.metrics.avg_month_pct == Approx(18.698));
  CHECK(a.metrics.ann_return_pct == Approx(681.85));
  CHECK(a.metrics.hit_rate_pct == Approx(100.0));
  CHECK(a.metrics.sharpe == Approx(59.22));
  CHECK(a.metrics.max_dd_pct == Approx(0.0));

  const auto& bench = find(rows, "BENCH_all");
  CHECK(bench.metrics.n_months == 2);
  CHECK(bench.metrics.avg_month_pct == Approx(23.696));
  CHECK(bench.metrics.ann_return_pct == Approx(1175.52));
  CHECK(bench.metrics.sharpe == Approx(21.03));

  // The overlay differs from A_darvas precisely because CCC breaks out in
  // both periods but is excluded from the durable set -- this is the
  // scenario that would silently pass if the overlay filter were wired
  // to the wrong set or the wrong ticker-name normalization.
  const auto& dur = find(rows, "D_darvas_durable");
  CHECK(dur.metrics.n_months == 2);
  CHECK(dur.metrics.avg_month_pct == Approx(20.656));
  CHECK(dur.metrics.ann_return_pct == Approx(851.16));
  CHECK(dur.metrics.sharpe == Approx(51.81));
}

TEST_CASE("run_market omits D_darvas_durable entirely when overlay is false",
          "[pit_global]") {
  auto tickers = make_fixture();
  for (int k = 0; k < 20; ++k) {
    TickerHistory filler;
    filler.ticker = "FILLER" + std::to_string(k);
    date::sys_days start = d(2024, 4, 1);
    for (int i = 0; i < 5; ++i) {
      filler.dates.push_back(start + date::days{i});
      filler.close.push_back(10.0);
    }
    tickers.push_back(filler);
  }
  auto rows = run_market("US", tickers, /*overlay=*/false, {}, 20, 20);
  REQUIRE(rows.size() == 2);
  for (const auto& r : rows) CHECK(r.arm != "D_darvas_durable");
}
