// Golden values generated by running hft_selection.py's actual functions
// on fixed synthetic OHLC/return/price series.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/hft_selection.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
// np.random.seed(11); high/low/close synthetic OHLC, n=20
const std::vector<double> kHigh = {
    102.65113122, 102.81136074, 102.19666579, 99.42756210,  99.36959725,  99.44668446,
    98.94762603,  98.61440942,  98.93728076,  98.42823886,  96.80924986,  96.63444558,
    97.02953505,  97.84007213,  96.28553851,  95.38594432,  96.62261917,  98.31255244,
    98.16869842,  97.25444911};
const std::vector<double> kLow = {
    100.72710364, 101.26913543, 100.94343984, 97.77320070, 97.27035924, 98.35235302,
    97.91652656,  96.45858732,  97.48735275,  96.37649244, 94.70724828, 94.23508864,
    95.42904240,  96.30241524,  94.07568832,  93.23920768, 94.64369706, 96.09610258,
    96.20537613,  94.81828303};
const std::vector<double> kClose = {
    101.58944209, 102.18319966, 101.83995280, 98.50099990, 98.38695744, 98.81892084,
    98.40900047,  97.28149956,  97.92392277,  97.55815533, 95.72990457, 95.50846752,
    96.37325964,  97.02244174,  95.10118399,  94.11399329, 95.80948156, 97.40414995,
    97.32756506,  96.26154282};
}  // namespace

TEST_CASE("avg_range and range_stability match Python", "[hft_selection]") {
  CHECK(avg_range(kHigh, kLow, kClose) == Approx(0.018924599939640754));
  CHECK(range_stability(kHigh, kLow, kClose) == Approx(0.004414680896727053));
}

// python3: corwin_schultz_spread(high[-5:], low[-5:]) -> 0.0046241847971778376
TEST_CASE("corwin_schultz_spread matches Python on the trailing 5 bars", "[hft_selection]") {
  std::vector<double> h5(kHigh.end() - 5, kHigh.end());
  std::vector<double> l5(kLow.end() - 5, kLow.end());
  CHECK(corwin_schultz_spread(h5, l5) == Approx(0.0046241847971778376));
}

TEST_CASE("efficiency_ratio matches Python", "[hft_selection]") {
  CHECK(efficiency_ratio(kClose) == Approx(0.29158101038529183));
}

// python3: lag1_autocorr(rets) on a 30-element seeded return series -> -0.02965747980993421
TEST_CASE("lag1_autocorr matches Python", "[hft_selection]") {
  std::vector<double> rets = {
      -0.00051964, 0.00055598,  0.01041797,  0.00628370,  0.00745388,  0.00855527,
      -0.00205864, 0.00117286,  0.01128144,  0.00006313,  -0.00613200, -0.00686844,
      0.01610992,  0.00344614,  0.00691924,  0.00224058,  0.00162342,  -0.00128615,
      -0.01275456, -0.00032002, -0.01061857, 0.00494684,  -0.00457723, 0.00992091,
      -0.01476442, -0.00115901, 0.00644159,  -0.00426061, -0.00464019, -0.00348588};
  CHECK(lag1_autocorr(rets) == Approx(-0.02965747980993421));
}

// python3: ou_half_life on a 50-bar mean-reverting-to-100 series -> 1.6670590843856328
TEST_CASE("ou_half_life matches Python on a mean-reverting series", "[hft_selection]") {
  std::vector<double> p = {
      100.00000000, 100.22061374, 99.98899454,  101.20768177, 100.71933118, 100.55833674,
      101.18207628, 100.37283719, 99.96516771,  100.06941901, 99.88365833,  99.32217852,
      99.42308671,  99.41674622,  99.89345816,  99.09302645,  99.01502899,  99.88621580,
      100.84901656, 99.83872182,  100.20952903, 99.65636638,  99.33102989,  99.09578133,
      99.15579297,  99.90727499,  100.29130313, 100.23348431, 99.98178358,  99.98889293,
      99.93925983,  100.35400854, 99.93202016,  99.94931666,  99.91398786,  99.91363742,
      100.06415503, 100.14373856, 100.76804128, 100.49419109, 101.12669991, 100.63576343,
      100.20616869, 100.19468718, 100.31400026, 100.35460639, 100.89420616, 101.19561580,
      101.08415126, 100.59073775};
  CHECK(ou_half_life(p) == Approx(1.6670590843856328));
}

// python3: ou_half_life on an accelerating/explosive series -> np.inf (not mean-reverting)
TEST_CASE("ou_half_life returns +infinity for a non-mean-reverting explosive series",
          "[hft_selection]") {
  std::vector<double> p3;
  for (int i = 0; i < 20; ++i) p3.push_back(100.0 + i + 0.02 * i * i);
  CHECK(std::isinf(ou_half_life(p3)));
  CHECK(ou_half_life(p3) > 0);
}

TEST_CASE("ou_half_life returns NaN with fewer than 4 prices", "[hft_selection]") {
  std::vector<double> p = {1.0, 2.0, 3.0};
  CHECK(std::isnan(ou_half_life(p)));
}

TEST_CASE("archetype_scores composites match hand-computed z-score sums", "[hft_selection]") {
  // Two stocks: A has low range/toxicity (good market-maker candidate),
  // B has high range/toxicity/persistence (good latency candidate).
  std::vector<HftFeatures> feat = {
      {1.0, 0.1, 0.2, -0.3, -0.1, 20.0, std::nullopt, std::nullopt},
      {5.0, 0.8, 0.9, 0.4, 0.5, 100.0, std::nullopt, std::nullopt},  // half_life=100 clips to 60
  };
  auto scores = archetype_scores(feat);
  REQUIRE(scores.size() == 2);
  // Stock A (low range/toxicity) should score higher on market_making than B.
  CHECK(scores[0].market_making > scores[1].market_making);
  // Stock B (high efficiency/persistence) should score higher on latency than A.
  CHECK(scores[1].latency > scores[0].latency);
  // Neither row has peer_corr -> etf_arb is absent for the whole batch.
  CHECK_FALSE(scores[0].etf_arb.has_value());
  CHECK_FALSE(scores[1].etf_arb.has_value());
}

TEST_CASE("archetype_scores computes etf_arb only when at least one row has peer_corr",
          "[hft_selection]") {
  std::vector<HftFeatures> feat = {
      {1.0, 0.1, 0.2, -0.3, -0.1, 20.0, 0.8, 0.02},
      {2.0, 0.2, 0.3, -0.1, 0.0, 25.0, 0.3, 0.01},
  };
  auto scores = archetype_scores(feat);
  CHECK(scores[0].etf_arb.has_value());
  CHECK(scores[1].etf_arb.has_value());
}
