// Golden values generated by running meta_screen.py's actual fuse().
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "bazaartalks/quant_core/meta_screen.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

// python3: fuse({'durability':80,'valuation':60,'momentum':90,'ml_signal':70,
//                'quality':50,'pead':40,'liquidity':30}) -> 64.0
TEST_CASE("fuse with every component present matches Python", "[meta_screen]") {
  ScreenComponents c{80, 60, 90, 70, 50, 40, 30};
  CHECK(fuse(c) == Approx(64.0));
}

// same components + triple_hit gate -> 74.0 (64 + 10)
TEST_CASE("fuse adds gate_bonus once per satisfied gate", "[meta_screen]") {
  ScreenComponents c{80, 60, 90, 70, 50, 40, 30};
  CHECK(fuse(c, ScreenWeights{}, /*num_gates_satisfied=*/1) == Approx(74.0));
}

// python3: fuse({'durability':80,'valuation':None,'momentum':90,
//                'ml_signal':nan,'quality':None,'pead':None,'liquidity':None})
// -> 84.44444444444444 (weights renormalise over durability+momentum only)
TEST_CASE("fuse renormalises weights when components are missing", "[meta_screen]") {
  ScreenComponents c;
  c.durability = 80;
  c.momentum = 90;
  // valuation, ml_signal, quality, pead, liquidity all absent (nullopt)
  CHECK(fuse(c) == Approx(84.44444444444444));
}

TEST_CASE("fuse returns 0 when every component is absent", "[meta_screen]") {
  ScreenComponents c;  // all nullopt
  CHECK(fuse(c) == Approx(0.0));
}

// python3: near-max components (95 each) + 2 satisfied gates -> clamps to 100.0
TEST_CASE("fuse clamps to 100 even with multiple gate bonuses", "[meta_screen]") {
  ScreenComponents c{95, 95, 95, 95, 95, 95, 95};
  CHECK(fuse(c, ScreenWeights{}, /*num_gates_satisfied=*/2) == Approx(100.0));
}
