// Golden values generated by running net_of_cost.py's actual functions.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/net_of_cost.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

TEST_CASE("amihud_impact clips to [0, 0.5] and matches Python", "[cost_models]") {
  CHECK(amihud_impact(0.0001, 500000) == Approx(0.5));   // clipped
  CHECK(amihud_impact(1e-8, 1000) == Approx(1e-05));
  CHECK(amihud_impact(-0.5, 1000) == Approx(0.0));        // non-positive illiq -> 0
  CHECK(amihud_impact(0.1, 0) == Approx(0.0));            // non-positive trade_value -> 0
}

TEST_CASE("round_trip_cost matches Python defaults and custom inputs", "[cost_models]") {
  CHECK(round_trip_cost() == Approx(0.002));
  CHECK(round_trip_cost(0.001, 0.002, 1e-8, 1000) == Approx(0.00602));
}

TEST_CASE("net_spread and break_even_cost match Python", "[cost_models]") {
  CHECK(net_spread(0.108, 0.0010, 0.5) == Approx(0.1075));
  CHECK(break_even_cost(0.0424, 1.0) == Approx(0.0424));
  CHECK(std::isinf(break_even_cost(0.01, 0.0)));  // turnover <= 0 -> +infinity, matches Python
}

TEST_CASE("survives_costs matches Python's market lookup and threshold", "[cost_models]") {
  CHECK(survives_costs(0.108, "US", 0.5) == true);
  CHECK(survives_costs(0.004, "BR", 1.0) == true);
}

TEST_CASE("round_trip_cost_for_market matches ROUND_TRIP dict incl. short/long aliases",
          "[cost_models]") {
  CHECK(round_trip_cost_for_market("US") == Approx(0.0010));
  CHECK(round_trip_cost_for_market("IN") == Approx(0.0030));
  CHECK(round_trip_cost_for_market("India") == Approx(0.0030));
  CHECK(round_trip_cost_for_market("UNKNOWN_MARKET") == Approx(kDefaultRoundTrip));
}
