// Golden values generated by running stream_pipeline.py's _signal()
// formula (RSI(14)/rolling-60-max classification) directly against a
// closed-form (trig, not random) 80-bar synthetic close series -- same
// generator-formula approach as earlier phases' dvm_global/dvm_engine
// tests, so the formula is reproducible here instead of embedding
// literal arrays. See the commit message / PR description for the
// generation script.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/services/ticker_signal_pipeline.hpp"

using namespace bazaartalks::services::ticker_signal_pipeline;
using Catch::Approx;

namespace {
constexpr std::size_t kN = 80;

std::vector<double> gen_close(double seedbase, double trendslope, double wobble_amp,
                              double wobble_period, int rally_start = -1,
                              double rally_slope = 0.0) {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 + trendslope * di + wobble_amp * std::sin(di * 1.047 + seedbase) +
               wobble_amp * 0.3 * std::sin(di / wobble_period + seedbase);
    if (rally_start >= 0 && static_cast<int>(i) >= rally_start) {
      v += static_cast<double>(static_cast<int>(i) - rally_start + 1) * rally_slope;
    }
    out[i] = v;
  }
  return out;
}
}  // namespace

TEST_CASE("compute_ticker_signal matches _signal()'s BREAKOUT classification",
          "[ticker_signal_pipeline]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0, /*rally_start=*/70, /*rally_slope=*/1.3);
  auto r = compute_ticker_signal("A", close);
  CHECK(r.ticker == "A");
  CHECK(r.signal == "BREAKOUT");
  REQUIRE(r.rsi.has_value());
  REQUIRE(r.close.has_value());
  CHECK(r.rsi.value() == Approx(81.7));
  CHECK(r.close.value() == Approx(125.9));
}

TEST_CASE("compute_ticker_signal matches _signal()'s OVERSOLD classification",
          "[ticker_signal_pipeline]") {
  auto close = gen_close(1.7, -0.3, 1.0, 9.0);
  auto r = compute_ticker_signal("B", close);
  CHECK(r.signal == "OVERSOLD");
  CHECK(r.rsi.value() == Approx(23.1));
  CHECK(r.close.value() == Approx(76.44));
}

TEST_CASE("compute_ticker_signal matches _signal()'s NEUTRAL classification",
          "[ticker_signal_pipeline]") {
  auto close = gen_close(2.9, 0.0, 0.5, 20.0);
  auto r = compute_ticker_signal("C", close);
  CHECK(r.signal == "NEUTRAL");
  CHECK(r.rsi.value() == Approx(42.1));
  CHECK(r.close.value() == Approx(99.73));
}

TEST_CASE("compute_ticker_signal returns NO_DATA below the 60-bar minimum",
          "[ticker_signal_pipeline]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0);
  close.resize(59);
  auto r = compute_ticker_signal("SHORT", close);
  CHECK(r.signal == "NO_DATA");
  CHECK(!r.rsi.has_value());
  CHECK(!r.close.has_value());
}

TEST_CASE("to_json matches _signal()'s dict shape, omitting rsi/close for NO_DATA",
          "[ticker_signal_pipeline]") {
  TickerSignalResult no_data{"X", "NO_DATA", std::nullopt, std::nullopt};
  CHECK(to_json(no_data) == R"({"signal":"NO_DATA","ticker":"X"})");

  TickerSignalResult withdata{"Y", "BREAKOUT", 81.7, 125.9};
  auto j = to_json(withdata);
  CHECK(j.find("\"ticker\":\"Y\"") != std::string::npos);
  CHECK(j.find("\"signal\":\"BREAKOUT\"") != std::string::npos);
  CHECK(j.find("\"rsi\":81.7") != std::string::npos);
  CHECK(j.find("\"close\":125.9") != std::string::npos);
}
