// Golden values generated by running darvas_volume.py's actual
// darvas_box()/box_state() on a fixed synthetic 45-bar OHLC series
// (np.random.seed(17)).
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/darvas_volume.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {
const std::vector<double> kHigh = {
    100.49608797, 99.47747923,  100.42986084, 100.30798206, 101.45049606, 102.37189216,
    102.39912569, 102.25332806, 101.81382807, 101.56499084, 102.70993031, 103.61018417,
    102.19445178, 102.59962788, 103.01597826, 101.99583489, 102.72702261, 102.14485663,
    101.49227033, 101.38740087, 101.28188582, 101.26689257, 101.82424721, 101.62807580,
    101.34745376, 100.98532286, 100.75299561, 101.14237972, 100.40903603, 100.62729960,
    101.45061577, 101.25721457, 101.04136092, 100.85726256, 101.97408173, 102.28252519,
    102.58163724, 102.88748476, 102.24188560, 100.95835494, 100.46196246, 102.40001008,
    102.47323014, 101.68745394, 101.81339738};
const std::vector<double> kLow = {
    99.52136536,  98.65165885,  98.60493964,  99.50094324,  100.01043833, 101.06524089,
    100.67508576, 100.36210158, 101.09076550, 100.44699580, 101.93052859, 102.39051855,
    100.95495927, 101.27295498, 101.49656057, 100.47257888, 101.14901026, 101.43265631,
    100.20558023, 100.64023559, 99.67433360,  100.30044945, 100.67293805, 100.09469798,
    100.21884877, 99.84904459,  99.33807400,  99.78567813,  98.83384941,  99.30309100,
    99.79375727,  100.06515019, 99.90265360,  100.20512396, 100.39683828, 101.02356932,
    101.46084884, 101.55079162, 101.07428862, 99.59228220,  99.01683074,  101.19114460,
    100.78584925, 100.99433375, 101.13191192};

// python3: np.random.seed(17); close = 100 + cumsum(normal(0,0.5,45)); close[-1]
constexpr double kCloseLast = 101.51788826042929;
}  // namespace

// python3: darvas_box(high, low, lookback=40, confirm=3) ->
//   {'top': 103.6101841682627, 'bottom': 98.83384941218314, 'len': 33, 'held': True}
TEST_CASE("darvas_box matches Python on a fixed synthetic OHLC series", "[darvas_volume]") {
  auto box = darvas_box(kHigh, kLow, 40, 3);
  CHECK(box.top == Approx(103.6101841682627));
  CHECK(box.bottom == Approx(98.83384941218314));
  CHECK(box.len == 33);
  CHECK(box.held == true);
}

// python3: box_state(close[-1], ..., box, vol[-1], mean(vol[-11:-1])) ->
//   {'state': 'in_box', 'position': 0.562, 'vol_confirmed': False}
TEST_CASE("box_state classifies in_box and matches Python's position", "[darvas_volume]") {
  DarvasBox box{103.6101841682627, 98.83384941218314, 33, true};
  auto state = box_state(kCloseLast, box, /*vol_last=*/2000, /*vol_avg=*/3000);
  CHECK(state.state == "in_box");
  REQUIRE(state.position.has_value());
  CHECK(*state.position == Approx(0.562));
  CHECK(state.vol_confirmed == false);
}

// python3: box_state(102.0, ..., {top:100,bottom:95}, 8000, 3000) ->
//   {'state': 'breakout', 'position': 1.2, 'vol_confirmed': True}
TEST_CASE("box_state classifies breakout, clips position, and confirms volume",
          "[darvas_volume]") {
  DarvasBox box{100.0, 95.0, 10, true};
  auto state = box_state(102.0, box, 8000, 3000);
  CHECK(state.state == "breakout");
  REQUIRE(state.position.has_value());
  CHECK(*state.position == Approx(1.2));  // clipped at 1.2 even though raw pos = 1.4
  CHECK(state.vol_confirmed == true);
}

TEST_CASE("box_state returns no_box for a degenerate (top<=bottom) box", "[darvas_volume]") {
  DarvasBox degenerate{95.0, 100.0, 0, false};  // top < bottom, invalid
  auto state = box_state(97.0, degenerate, 1000, 1000);
  CHECK(state.state == "no_box");
  CHECK_FALSE(state.position.has_value());
  CHECK_FALSE(state.vol_confirmed);
}

TEST_CASE("accumulation_score produces a finite composite for a well-formed batch",
          "[darvas_volume]") {
  std::vector<AccumulationFeatures> feat = {
      {0.8, 0.7, 0.2, 1.5, 0.5},
      {-0.5, -0.4, -0.1, 0.6, -0.3},
  };
  auto scores = accumulation_score(feat);
  REQUIRE(scores.size() == 2);
  CHECK(std::isfinite(scores[0]));
  CHECK(std::isfinite(scores[1]));
  // Stock 0 has stronger OBV/AD up-trends and a higher up/down volume
  // ratio -- it should score as more "accumulated" than stock 1.
  CHECK(scores[0] > scores[1]);
}
