// Golden tests generated by running the ACTUAL formulas from
// dvm_engine.py's momentum_score() (RSI/MACD/ADX-DMI) and
// darvas_volume.py's obv()/chaikin_ad()/chaikin_money_flow()/
// up_down_volume_ratio() against a fixed synthetic OHLCV series
// (np.random.seed(42), n=40 bars) via pandas/numpy directly. See the
// migration-plan validation strategy: these are the reference values a
// human ran the Python originals to produce, not hand-derived expectations.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/stats/technical_indicators.hpp"

using namespace bazaartalks::stats;
using Catch::Approx;

namespace {

// python3 -c "... print(list(np.round(close,6))) ..." (see commit message /
// PR description for the full generation script) -- np.random.seed(42), n=40.
const std::vector<double> kClose = {
    101.093428, 100.914969, 102.323114, 105.54226,  105.153541, 104.766288, 108.180019,
    109.948621, 109.026209, 110.3183,   109.40615,  108.496482, 109.130019, 105.063223,
    101.543778, 100.503386, 98.56803,   99.286093,  97.582296,  94.923561,  97.800977,
    97.457155,  97.686234,  95.000355,  94.061024,  94.363755,  92.285877,  93.071595,
    92.046619,  91.601677,  90.590932,  94.037515,  94.106168,  92.209531,  93.818671,
    91.621731,  92.096081,  88.578619,  86.31422,   86.740372};

const std::vector<double> kHigh = {
    101.466699, 101.001438, 102.382281, 105.701156, 105.9309,   105.143365, 108.429179,
    110.529767, 109.213526, 111.290778, 109.583433, 108.705382, 109.499382, 105.384547,
    102.067236, 100.97137,  98.98163,   99.439595,  97.743923,  95.386572,  98.035295,
    97.547624,  98.226603,  95.568555,  94.443159,  95.003654,  92.319105,  93.538597,
    92.213056,  91.897147,  90.754628,  94.760681,  94.123025,  92.930907,  95.047576,
    91.998251,  92.136165,  88.711047,  86.353821,  87.602385};

const std::vector<double> kLow = {
    100.982391, 100.734779, 101.567,   105.268763, 104.728461, 104.503452, 107.684878,
    109.767893, 108.73742,  110.035186, 109.353045, 107.971009, 108.746944, 104.891097,
    101.344697, 99.767945,  98.42209,   99.156497,  97.579801,  94.812222,  97.108853,
    97.25218,   97.518842,  94.619271,  93.98517,   94.173116,  91.415535,  92.990354,
    91.928086,  91.56758,   89.721816,  94.025049,  94.077828,  91.073859,  93.728435,
    91.483589,  92.080097,  88.061019,  85.82101,   86.414257};

const std::vector<double> kVolume = {5218, 9958, 5389, 3327, 9004, 3931, 8777, 1197, 8125,
                                      2930, 7287, 9800, 5282, 3511, 1659, 3811, 8098, 7546,
                                      2986, 9338, 3911, 2734, 2843, 9680, 3976, 2959, 6759,
                                      7694, 3385, 5736, 2802, 9155, 9120, 7616, 6534, 5061,
                                      1262, 7287, 9815, 3049};

}  // namespace

TEST_CASE("rsi matches Python's momentum_score() RSI(14) on last 5 bars", "[indicators]") {
  auto r = rsi(kClose, 14);
  REQUIRE(r.size() == kClose.size());
  CHECK(r[35] == Approx(34.41329084495513));
  CHECK(r[36] == Approx(35.26153557867096));
  CHECK(r[37] == Approx(33.780288068557624));
  CHECK(r[38] == Approx(31.66102918118513));
  CHECK(r[39] == Approx(32.05804914725584));
}

TEST_CASE("macd matches Python's ewm(12/26/9) MACD on last 5 bars", "[indicators]") {
  auto m = macd(kClose, 12, 26, 9);
  CHECK(m.macd_line[35] == Approx(-2.1676954130635124));
  CHECK(m.macd_line[36] == Approx(-2.107808034296596));
  CHECK(m.macd_line[37] == Approx(-2.303478865974725));
  CHECK(m.macd_line[38] == Approx(-2.6025322205915415));
  CHECK(m.macd_line[39] == Approx(-2.774175741071403));

  CHECK(m.signal_line[35] == Approx(-2.2945479520433985));
  CHECK(m.signal_line[36] == Approx(-2.257190269885253));
  CHECK(m.signal_line[37] == Approx(-2.2664499122556268));
  CHECK(m.signal_line[38] == Approx(-2.33367754402909));
  CHECK(m.signal_line[39] == Approx(-2.421788895445057));

  CHECK(m.histogram[35] == Approx(0.12685253897988602));
  CHECK(m.histogram[36] == Approx(0.1493822355886567));
  CHECK(m.histogram[37] == Approx(-0.0370289537190982));
  CHECK(m.histogram[38] == Approx(-0.26885467656245154));
  CHECK(m.histogram[39] == Approx(-0.3523868456263459));
}

TEST_CASE("adx_dmi matches Python's simplified ADX/DMI(14) on last 5 bars", "[indicators]") {
  auto a = adx_dmi(kHigh, kLow, 14);
  CHECK(a.plus_di[35] == Approx(81.6028176348003));
  CHECK(a.plus_di[36] == Approx(81.50889498567172));
  CHECK(a.plus_di[37] == Approx(84.05890209799882));
  CHECK(a.plus_di[38] == Approx(83.40648789464652));
  CHECK(a.plus_di[39] == Approx(87.30547829241864));

  CHECK(a.minus_di[35] == Approx(140.81422584819634));
  CHECK(a.minus_di[36] == Approx(150.11684260041744));
  CHECK(a.minus_di[37] == Approx(166.5168960493294));
  CHECK(a.minus_di[38] == Approx(181.88279574026308));
  CHECK(a.minus_di[39] == Approx(175.37748755215677));

  CHECK(a.adx[35] == Approx(40.430728421322954));
  CHECK(a.adx[36] == Approx(39.46934955279546));
  CHECK(a.adx[37] == Approx(37.37908409383583));
  CHECK(a.adx[38] == Approx(35.59511499334379));
  CHECK(a.adx[39] == Approx(33.99284572811905));
}

TEST_CASE("obv matches Python's cumulative signed-volume OBV on last 5 bars", "[indicators]") {
  auto o = obv(kClose, kVolume);
  CHECK(o[35] == Approx(-48593.0));
  CHECK(o[36] == Approx(-47331.0));
  CHECK(o[37] == Approx(-54618.0));
  CHECK(o[38] == Approx(-64433.0));
  CHECK(o[39] == Approx(-61384.0));
}

TEST_CASE("chaikin_ad matches Python's cumulative money-flow-volume line on last 5 bars",
          "[indicators]") {
  auto ad = chaikin_ad(kHigh, kLow, kClose, kVolume);
  CHECK(ad[35] == Approx(-28314.565227791238));
  CHECK(ad[36] == Approx(-28857.007549549056));
  CHECK(ad[37] == Approx(-24539.126926948065));
  CHECK(ad[38] == Approx(-16183.132259960272));
  CHECK(ad[39] == Approx(-17558.3653776758));
}

TEST_CASE("chaikin_money_flow(20) matches Python", "[indicators]") {
  double cmf = chaikin_money_flow(kHigh, kLow, kClose, kVolume, 20);
  CHECK(cmf == Approx(-0.0815813755063414));
}

TEST_CASE("up_down_volume_ratio matches Python", "[indicators]") {
  double r = up_down_volume_ratio(kClose, kVolume);
  CHECK(r == Approx(0.5688084350128899));
}

TEST_CASE("up_down_volume_ratio edge cases match Python's +inf/NaN convention",
          "[indicators]") {
  // all up-closes, zero down-volume -> +infinity
  std::vector<double> rising_close = {100, 101, 102, 103};
  std::vector<double> vol = {10, 20, 30, 40};
  double r_up = up_down_volume_ratio(rising_close, vol);
  CHECK(std::isinf(r_up));
  CHECK(r_up > 0);

  // flat series -> no up or down volume -> NaN
  std::vector<double> flat_close = {100, 100, 100, 100};
  double r_flat = up_down_volume_ratio(flat_close, vol);
  CHECK(std::isnan(r_flat));
}

// python3: pd.Series(x).rolling(5).std() on a fixed 20-bar random-walk
// (np.random.seed(50))
TEST_CASE("rolling_std matches pandas' sample (ddof=1) rolling std", "[indicators]") {
  std::vector<double> x = {98.43964789, 98.40867029, 97.78774186, 96.32316138, 97.73510750,
                            97.25837536, 96.47790614, 97.54817388, 96.26588128, 94.93840238,
                            95.06474002, 95.92693374, 96.62367070, 96.28910552, 95.29157945,
                            96.89048775, 100.20456309, 101.19233355, 101.31619981, 102.05898520};
  auto s = rolling_std(x, 5);
  for (int i = 0; i < 4; ++i) CHECK(std::isnan(s[i]));
  CHECK(s[4] == Approx(0.85824757));
  CHECK(s[5] == Approx(0.77573354));
  CHECK(s[9] == Approx(1.02074276));
  CHECK(s[19] == Approx(2.03417959));
}

// python3: pd.Series(x).ewm(span=3, adjust=False).mean() on the same series
TEST_CASE("ewm_mean_no_adjust matches pandas' adjust=False recursive EMA", "[indicators]") {
  std::vector<double> x = {98.43964789, 98.40867029, 97.78774186, 96.32316138, 97.73510750,
                            97.25837536, 96.47790614, 97.54817388, 96.26588128, 94.93840238,
                            95.06474002, 95.92693374, 96.62367070, 96.28910552, 95.29157945,
                            96.89048775, 100.20456309, 101.19233355, 101.31619981, 102.05898520};
  auto e = ewm_mean_no_adjust(x, 3);
  CHECK(e[0] == Approx(98.43964789));
  CHECK(e[1] == Approx(98.42415909));
  CHECK(e[19] == Approx(101.29061503));
}
