// Golden values for momentum_score() generated by running the ACTUAL
// dvm_engine.py momentum_score() against a closed-form (trig/linear, not
// random) 260-bar synthetic OHLCV series -- same generator-formula
// approach as libs/quant_core/dvm_global's tests, so the same formula is
// reproducible here in C++ instead of embedding literal arrays. See the
// commit message / PR description for the generation script.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>
#include <cmath>

#include "bazaartalks/quant_core/dvm_engine.hpp"

using namespace bazaartalks::quant_core;
using Catch::Approx;

namespace {

constexpr std::size_t kN = 260;

std::vector<double> gen_close(double seedbase, double trendslope, double wobble_amp,
                              double wobble_period, int rally_start = -1,
                              double rally_slope = 0.0) {
  std::vector<double> out(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    double v = 100.0 + trendslope * di + wobble_amp * std::sin(di / wobble_period + seedbase);
    if (rally_start >= 0 && static_cast<int>(i) >= rally_start) {
      v += static_cast<double>(static_cast<int>(i) - rally_start + 1) * rally_slope;
    }
    out[i] = v;
  }
  return out;
}

struct Ohlcv {
  std::vector<double> close, high, low, volume;
};

Ohlcv build_ohlcv(const std::vector<double>& close, double seedbase) {
  Ohlcv o;
  o.close = close;
  o.high.resize(kN);
  o.low.resize(kN);
  o.volume.resize(kN);
  for (std::size_t i = 0; i < kN; ++i) {
    double di = static_cast<double>(i);
    o.high[i] = close[i] + 0.3 + 0.2 * std::abs(std::sin(di * 0.7 + seedbase));
    o.low[i] = close[i] - 0.3 - 0.2 * std::abs(std::cos(di * 0.5 + seedbase));
    o.volume[i] = 2000.0 + 500.0 * std::sin(di * 0.3 + seedbase) + 1500.0;
  }
  return o;
}

}  // namespace

TEST_CASE("momentum_score matches dvm_engine.py on a rallying series", "[dvm_engine]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0, /*rally_start=*/230, /*rally_slope=*/1.3);
  auto o = build_ohlcv(close, 0.3);
  o.volume.back() *= 3.0;
  double M = momentum_score(o.close, o.high, o.low, o.volume);
  CHECK(M == Approx(83.3333333333).epsilon(1e-6));
}

TEST_CASE("momentum_score matches dvm_engine.py on a mild-downtrend series", "[dvm_engine]") {
  auto close = gen_close(1.7, -0.04, 2.5, 9.0);
  auto o = build_ohlcv(close, 1.7);
  double M = momentum_score(o.close, o.high, o.low, o.volume);
  CHECK(M == Approx(55.9558895529).epsilon(1e-6));
}

TEST_CASE("momentum_score returns NaN below the 220-bar minimum", "[dvm_engine]") {
  auto close = gen_close(0.3, 0.12, 3.0, 12.0);
  close.resize(219);
  auto o = build_ohlcv(close, 0.3);
  o.high.resize(219);
  o.low.resize(219);
  o.volume.resize(219);
  double M = momentum_score(o.close, o.high, o.low, o.volume);
  CHECK(std::isnan(M));
}

// durability_score(): cross-checked directly against the module's own
// scoring-formula lines (durability_score()'s `subs` computation), not
// the full function -- that requires live EDGAR access via
// pit_fundamentals.as_of()/piotroski_asof(), reserved for Phase 6.
TEST_CASE("durability_score matches dvm_engine.py's subs-then-mean formula", "[dvm_engine]") {
  // roe=25 (>20 -> 90), de=0.5 (<1 -> 85), fcf positive (-> 80),
  // revenue growing (-> 75), F=7 (-> 7/9*100=77.777...)
  // mean = (90+85+80+75+77.77777...)/5 = 81.555555...
  double d1 = durability_score(25.0, 0.5, true, true, 7.0);
  CHECK(d1 == Approx((90.0 + 85.0 + 80.0 + 75.0 + 700.0 / 9.0) / 5.0).epsilon(1e-9));

  // Every input absent/negative: roe=None (-> 15), de=None (-> 20),
  // fcf=None (-> 20), revenue not growing (-> 35), F=None (-> 50)
  // mean = (15+20+20+35+50)/5 = 28
  double d2 = durability_score(std::nullopt, std::nullopt, std::nullopt, false, std::nullopt);
  CHECK(d2 == Approx(28.0).epsilon(1e-9));

  // roe=0.0 (present but falls through every `roe > N` check, same
  // outcome as None) -> 15; de=1.5 (not <1, but <2 -> 50);
  // fcf=false (present, not positive -> 20); F=9 (-> 100)
  double d3 = durability_score(0.0, 1.5, false, false, 9.0);
  CHECK(d3 == Approx((15.0 + 50.0 + 20.0 + 35.0 + 100.0) / 5.0).epsilon(1e-9));
}

TEST_CASE("classification_letter matches g(x)'s is-not-None-and->=50 check", "[dvm_engine]") {
  CHECK(classification_letter(72.0) == 'G');
  CHECK(classification_letter(50.0) == 'G');   // >=50 boundary
  CHECK(classification_letter(49.9) == 'B');
  CHECK(classification_letter(0.0) == 'B');    // present but 0 -> B (not None-like here)
  CHECK(classification_letter(std::nullopt) == 'B');
}

TEST_CASE("classification_label matches the LABELS dict", "[dvm_engine]") {
  CHECK(classification_label("GGG") == "Strong Performer");
  CHECK(classification_label("GGB") == "Value Under Radar");
  CHECK(classification_label("GBG") == "Expensive Durable Mover");
  CHECK(classification_label("GBB") == "Expensive Quality");
  CHECK(classification_label("BGG") == "Cheap Turnaround Mover");
  CHECK(classification_label("BGB") == "Deep Value / Watch");
  CHECK(classification_label("BBG") == "Momentum Trap");
  CHECK(classification_label("BBB") == "Weak / Avoid");
  CHECK(classification_label("XYZ") == "-");
}

TEST_CASE("SCREENS predicates match dvm_engine.py's SCREENS dict", "[dvm_engine]") {
  // high_dvm: r["D"] and r["V"] and r["M"] and (D+V+M)/3 >= 65
  CHECK(screen_high_dvm(DvmRow{70.0, 70.0, 70.0}) == true);
  CHECK(screen_high_dvm(DvmRow{70.0, 70.0, 40.0}) == false);       // mean < 65
  CHECK(screen_high_dvm(DvmRow{std::nullopt, 70.0, 70.0}) == false);  // D falsy (None)
  CHECK(screen_high_dvm(DvmRow{0.0, 70.0, 70.0}) == false);        // D falsy (0.0)

  // durable_momentum: (D or 0) >= 60 and M >= 60
  CHECK(screen_durable_momentum(DvmRow{65.0, std::nullopt, 65.0}) == true);
  CHECK(screen_durable_momentum(DvmRow{std::nullopt, std::nullopt, 65.0}) == false);
  CHECK(screen_durable_momentum(DvmRow{65.0, std::nullopt, 59.9}) == false);

  // value_under_radar: (D or 0) >= 55 and (V or 0) >= 55 and M < 50
  CHECK(screen_value_under_radar(DvmRow{60.0, 60.0, 30.0}) == true);
  CHECK(screen_value_under_radar(DvmRow{60.0, 60.0, 50.0}) == false);  // M not < 50
  CHECK(screen_value_under_radar(DvmRow{std::nullopt, 60.0, 30.0}) == false);

  // momentum_breakout: M >= 75
  CHECK(screen_momentum_breakout(DvmRow{std::nullopt, std::nullopt, 80.0}) == true);
  CHECK(screen_momentum_breakout(DvmRow{std::nullopt, std::nullopt, 74.9}) == false);
}
